In [1]:
import requests
import json
import re
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
source_dir = r'C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Maxxforce action\Consumers Energy Truck Vins\Source Data\\'
output_dir = r'C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Maxxforce action\Consumers Energy Truck Vins\Output\\'
fileName = r'Consumer Energy Truck VINs.xlsx'

In [4]:
df = pd.read_excel(source_dir + fileName)
df

    TechIdentNo  ConstructYear   Manufacturer Model number                VIN
0         54013           2013  INTERNATIONAL         7400  1HTWCAAN6DH302792
1         54023           2013  INTERNATIONAL         7400  1HTWCAAN8DH302793
2         54032           2012  INTERNATIONAL         7400  1HTMKAAN0CH081814
3         54033           2013  INTERNATIONAL         7400  1HTWCAAN4DJ325609
4         54042           2012  INTERNATIONAL         7400  1HTMKAAN9CH081813
5         54043           2013  INTERNATIONAL         7400  1HTWCAAN0DJ325610
6         54052           2012  INTERNATIONAL         7400  1HTWDAAN5CJ082162
7         54053           2013  INTERNATIONAL         7400  1HTWCAAN2DJ325611
8         54062           2012  INTERNATIONAL         7400  1HTWCAAR8CJ081805
9         54063           2013  INTERNATIONAL         7400  1HTWCAAN4DJ325612
10        54072           2012  INTERNATIONAL         7400  1HTWCAAN6CJ081797
11        54073           2013  INTERNATIONAL         7400  1HTWCAAN6DJ325613
12        54082           2012  INTERNATIONAL         7400  1HTWDAAR9CJ082166
13        54083           2013  INTERNATIONAL         7400  1HTWCAAN8DJ325614
14        55104           2014  INTERNATIONAL         7400  1HTWGAZR9EH095148
15        57004           2014  INTERNATIONAL         7400  1HTWGAAR5EH061185
16        57062           2012  INTERNATIONAL         7400  1HTWGAAR7CJ699931
17        57072           2012  INTERNATIONAL         7400  1HTWGAAR9CJ699932
18        57082           2012  INTERNATIONAL         7400  1HTWGAAR2CJ699934
19        57092           2012  INTERNATIONAL         7400  1HTWGAAR4CJ699935
20        57102           2012  INTERNATIONAL         7400  1HTWGAAR6CJ699936
21        58002           2012  INTERNATIONAL         7400  1HTWGAAR9CJ454144
22        58003           2013  INTERNATIONAL         7400  1HTWGAAR4DH201225
23        58012           2012  INTERNATIONAL         7400  1HTWGAAR0CJ454145
24        58013           2013  INTERNATIONAL         7400  1HTWGAAR6DJ329121
25        58022           2012  INTERNATIONAL         7400  1HTWGAAR2CJ454146
26        58023           2013  INTERNATIONAL         7400  1HTWGAAR8DJ329122
27        58033           2013  INTERNATIONAL         7400  1HTWGAARXDJ329123
28        58072           2012  INTERNATIONAL         7400  1HTWGAAR4CJ454147
29        58082           2012  INTERNATIONAL         7400  1HTWGAAR1CJ692151
..          ...            ...            ...          ...                ...
122       89573           2013  INTERNATIONAL         7400  1HTWGAAR4DJ131119
123       89583           2013  INTERNATIONAL         7400  1HTWGAAR0DJ131120
124       89593           2013  INTERNATIONAL         7400  1HTWGAAR2DJ131121
125       89603           2013  INTERNATIONAL         7400  1HTWGAAR4DJ131122
126       89613           2013  INTERNATIONAL         7400  1HTWGAAR6DJ131123
127       89623           2013  INTERNATIONAL         7400  1HTWGAAR8DJ131124
128       89633           2013  INTERNATIONAL         7400  1HTWJAAR3DJ166526
129       89643           2013  INTERNATIONAL         7400  1HTWJAAR3DJ131159
130       89653           2013  INTERNATIONAL         7400  1HTWGAAR5DJ131114
131       89663           2013  INTERNATIONAL         7400  1HTWGAAR7DJ131115
132       89673           2013  INTERNATIONAL         7400  1HTWGAAR9DJ131116
133       89683           2013  INTERNATIONAL         7400  1HTWGAAR0DJ131117
134       89693           2013  INTERNATIONAL         7400  1HTWJAAR5DJ131180
135       94004           2014  INTERNATIONAL         7400  1HTWGAAR5EH091206
136       96001           2011  INTERNATIONAL         7400  1HTWJAARXBJ383102
137       96003           2013  INTERNATIONAL         7400  1HTWGAARXDJ131321
138       96011           2011  INTERNATIONAL         7400  1HTWJAAR1BJ383103
139       96013           2013  INTERNATIONAL         7400  1HTWGAAR3DJ166492
140       96021           2012  INTERNATIONAL         7400  1HTWGAAR9CJ547228
141       97004           2014  INTERNATIONAL         7400  1HTWJAARXEJ468655
142       98002           2012  INTERNATIONAL         7400  1HTWGAAT3CJ547270
143       98032           2012  INTERNATIONAL         7400  1HTWGAAT4CJ547276
144       98042           2012  INTERNATIONAL         7400  1HTWGAAT9CJ547273
145       98052           2012  INTERNATIONAL         7400  1HTWGAAT8CJ547281
146       98062           2012  INTERNATIONAL         7400  1HTWGAAT8CJ699898
147       98072           2012  INTERNATIONAL         7400  1HTWGAATXCJ699899
148       99004           2014  INTERNATIONAL         7400  1HTWHAZR3EH768609
149       99822           2012  INTERNATIONAL         4300  1HTMMAAL3CH457396
150      Z77011           2011  INTERNATIONAL         7400  1HTWGAARXBJ383101
151      Z82001           2011  INTERNATIONAL         7300  1HTWBAAN5BJ383096

[152 rows x 5 columns]

In [5]:
df.iloc[:,4]

0      1HTWCAAN6DH302792
1      1HTWCAAN8DH302793
2      1HTMKAAN0CH081814
3      1HTWCAAN4DJ325609
4      1HTMKAAN9CH081813
5      1HTWCAAN0DJ325610
6      1HTWDAAN5CJ082162
7      1HTWCAAN2DJ325611
8      1HTWCAAR8CJ081805
9      1HTWCAAN4DJ325612
10     1HTWCAAN6CJ081797
11     1HTWCAAN6DJ325613
12     1HTWDAAR9CJ082166
13     1HTWCAAN8DJ325614
14     1HTWGAZR9EH095148
15     1HTWGAAR5EH061185
16     1HTWGAAR7CJ699931
17     1HTWGAAR9CJ699932
18     1HTWGAAR2CJ699934
19     1HTWGAAR4CJ699935
20     1HTWGAAR6CJ699936
21     1HTWGAAR9CJ454144
22     1HTWGAAR4DH201225
23     1HTWGAAR0CJ454145
24     1HTWGAAR6DJ329121
25     1HTWGAAR2CJ454146
26     1HTWGAAR8DJ329122
27     1HTWGAARXDJ329123
28     1HTWGAAR4CJ454147
29     1HTWGAAR1CJ692151
             ...
122    1HTWGAAR4DJ131119
123    1HTWGAAR0DJ131120
124    1HTWGAAR2DJ131121
125    1HTWGAAR4DJ131122
126    1HTWGAAR6DJ131123
127    1HTWGAAR8DJ131124
128    1HTWJAAR3DJ166526
129    1HTWJAAR3DJ131159
130    1HTWGAAR5DJ131114
131    1HTWGAAR7DJ131115
132    1HTWGAAR9DJ131116
133    1HTWGAAR0DJ131117
134    1HTWJAAR5DJ131180
135    1HTWGAAR5EH091206
136    1HTWJAARXBJ383102
137    1HTWGAARXDJ131321
138    1HTWJAAR1BJ383103
139    1HTWGAAR3DJ166492
140    1HTWGAAR9CJ547228
141    1HTWJAARXEJ468655
142    1HTWGAAT3CJ547270
143    1HTWGAAT4CJ547276
144    1HTWGAAT9CJ547273
145    1HTWGAAT8CJ547281
146    1HTWGAAT8CJ699898
147    1HTWGAATXCJ699899
148    1HTWHAZR3EH768609
149    1HTMMAAL3CH457396
150    1HTWGAARXBJ383101
151    1HTWBAAN5BJ383096
Name: VIN, Length: 152, dtype: object

# define VIN COLUMNS

In [8]:
x = 4

In [6]:
responses = pd.Series(None, index=range(len(df)))
responses

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
29    NaN
       ..
122   NaN
123   NaN
124   NaN
125   NaN
126   NaN
127   NaN
128   NaN
129   NaN
130   NaN
131   NaN
132   NaN
133   NaN
134   NaN
135   NaN
136   NaN
137   NaN
138   NaN
139   NaN
140   NaN
141   NaN
142   NaN
143   NaN
144   NaN
145   NaN
146   NaN
147   NaN
148   NaN
149   NaN
150   NaN
151   NaN
Length: 152, dtype: float64

In [9]:
for i in range(len(df)):
    print(i)
    VIN = df.iloc[i,x]
    r = requests.post('https://secure.maxxforce11and13.com/en/VinLookup',{'VinNumber':VIN})
    soup = BeautifulSoup(r.text,'lxml')
    target = soup.find('form').find('div',class_ = 'alert alert-danger')
    if target:
        result= re.search(r'( {32})([\w\s]*\.)',str(target))
        responses[i] = result.group(2)
    else:
        target = soup.find('form').find('div',class_ = 'alert alert-success')
        result= re.search(r'( {32})([\w\s]*\.)',str(target))
        responses[i] = result.group(2)
responses

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151

0      The VIN you entered is not included in the Set...
1      The VIN you entered is not included in the Set...
2      The VIN you entered is not included in the Set...
3      The VIN you entered is not included in the Set...
4      The VIN you entered is not included in the Set...
5      The VIN you entered is not included in the Set...
6      The VIN you entered is not included in the Set...
7      The VIN you entered is not included in the Set...
8      The VIN you entered is not included in the Set...
9      The VIN you entered is not included in the Set...
10     The VIN you entered is not included in the Set...
11     The VIN you entered is not included in the Set...
12     The VIN you entered is not included in the Set...
13     The VIN you entered is not included in the Set...
14     The VIN you entered is not included in the Set...
15     The VIN you entered is not included in the Set...
16     The VIN you entered is not included in the Set...
17     The VIN you entered is not included in the Set...
18     The VIN you entered is not included in the Set...
19     The VIN you entered is not included in the Set...
20     The VIN you entered is not included in the Set...
21     The VIN you entered is not included in the Set...
22     The VIN you entered is not included in the Set...
23     The VIN you entered is not included in the Set...
24     The VIN you entered is not included in the Set...
25     The VIN you entered is not included in the Set...
26     The VIN you entered is not included in the Set...
27     The VIN you entered is not included in the Set...
28     The VIN you entered is not included in the Set...
29     The VIN you entered is not included in the Set...
                             ...
122    The VIN you entered is not included in the Set...
123    The VIN you entered is not included in the Set...
124    The VIN you entered is not included in the Set...
125    The VIN you entered is not included in the Set...
126    The VIN you entered is not included in the Set...
127    The VIN you entered is not included in the Set...
128    The VIN you entered is not included in the Set...
129    The VIN you entered is not included in the Set...
130    The VIN you entered is not included in the Set...
131    The VIN you entered is not included in the Set...
132    The VIN you entered is not included in the Set...
133    The VIN you entered is not included in the Set...
134    The VIN you entered is not included in the Set...
135    The VIN you entered is not included in the Set...
136    The VIN you entered is not included in the Set...
137    The VIN you entered is not included in the Set...
138    The VIN you entered is not included in the Set...
139    The VIN you entered is not included in the Set...
140    The VIN you entered is not included in the Set...
141    The VIN you entered is not included in the Set...
142    The VIN you entered is not included in the Set...
143    The VIN you entered is not included in the Set...
144    The VIN you entered is not included in the Set...
145    The VIN you entered is not included in the Set...
146    The VIN you entered is not included in the Set...
147    The VIN you entered is not included in the Set...
148    The VIN you entered is not included in the Set...
149    The VIN you entered is not included in the Set...
150    The VIN you entered is not included in the Set...
151    The VIN you entered is not included in the Set...
Length: 152, dtype: object

In [10]:
df['Response'] = responses.values

In [11]:
df

,TechIdentNo,ConstructYear,Manufacturer,Model number,VIN,Response
0,54013,2013,INTERNATIONAL,7400,1HTWCAAN6DH302792,The VIN you entered is not included in the Set...
1,54023,2013,INTERNATIONAL,7400,1HTWCAAN8DH302793,The VIN you entered is not included in the Set...
2,54032,2012,INTERNATIONAL,7400,1HTMKAAN0CH081814,The VIN you entered is not included in the Set...
3,54033,2013,INTERNATIONAL,7400,1HTWCAAN4DJ325609,The VIN you entered is not included in the Set...
4,54042,2012,INTERNATIONAL,7400,1HTMKAAN9CH081813,The VIN you entered is not included in the Set...
5,54043,2013,INTERNATIONAL,7400,1HTWCAAN0DJ325610,The VIN you entered is not included in the Set...
6,54052,2012,INTERNATIONAL,7400,1HTWDAAN5CJ082162,The VIN you entered is not included in the Set...
7,54053,2013,INTERNATIONAL,7400,1HTWCAAN2DJ325611,The VIN you entered is not included in the Set...
8,54062,2012,INTERNATIONAL,7400,1HTWCAAR8CJ081805,The VIN you entered is not included in the Set...
9,54063,2013,INTERNATIONAL,7400,1HTWCAAN4DJ325612,The VIN you entered is not included in the Set...
10,54072,2012,INTERNATIONAL,7400,1HTWCAAN6CJ081797,The VIN you entered is not included in the Set...
11,54073,2013,INTERNATIONAL,7400,1HTWCAAN6DJ325613,The VIN you entered is not included in the Set...
12,54082,2012,INTERNATIONAL,7400,1HTWDAAR9CJ082166,The VIN you entered is not included in the Set...
13,54083,2013,INTERNATIONAL,7400,1HTWCAAN8DJ325614,The VIN you entered is not included in the Set...
14,55104,2014,INTERNATIONAL,7400,1HTWGAZR9EH095148,The VIN you entered is not included in the Set...
15,57004,2014,INTERNATIONAL,7400,1HTWGAAR5EH061185,The VIN you entered is not included in the Set...
16,57062,2012,INTERNATIONAL,7400,1HTWGAAR7CJ699931,The VIN you entered is not included in the Set...
17,57072,2012,INTERNATIONAL,7400,1HTWGAAR9CJ699932,The VIN you entered is not included in the Set...
18,57082,2012,INTERNATIONAL,7400,1HTWGAAR2CJ699934,The VIN you entered is not included in the Set...
19,57092,2012,INTERNATIONAL,7400,1HTWGAAR4CJ699935,The VIN you entered is not included in the Set...
20,57102,2012,INTERNATIONAL,7400,1HTWGAAR6CJ699936,The VIN you entered is not included in the Set...
21,58002,2012,INTERNATIONAL,7400,1HTWGAAR9CJ454144,The VIN you entered is not included in the Set...
22,58003,2013,INTERNATIONAL,7400,1HTWGAAR4DH201225,The VIN you entered is not included in the Set...
23,58012,2012,INTERNATIONAL,7400,1HTWGAAR0CJ454145,The VIN you entered is not included in the Set...
24,58013,2013,INTERNATIONAL,7400,1HTWGAAR6DJ329121,The VIN you entered is not included in the Set...
25,58022,2012,INTERNATIONAL,7400,1HTWGAAR2CJ454146,The VIN you entered is not included in the Set...
26,58023,2013,INTERNATIONAL,7400,1HTWGAAR8DJ329122,The VIN you entered is not included in the Set...
27,58033,2013,INTERNATIONAL,7400,1HTWGAARXDJ329123,The VIN you entered is not included in the Set...
28,58072,2012,INTERNATIONAL,7400,1HTWGAAR4CJ454147,The VIN you entered is not included in the Set...
29,58082,2012,INTERNATIONAL,7400,1HTWGAAR1CJ692151,The VIN you entered is not included in the Set...
...,...,...,...,...,...,...
122,89573,2013,INTERNATIONAL,7400,1HTWGAAR4DJ131119,The VIN you entered is not included in the Set...
123,89583,2013,INTERNATIONAL,7400,1HTWGAAR0DJ131120,The VIN you entered is not included in the Set...
124,89593,2013,INTERNATIONAL,7400,1HTWGAAR2DJ131121,The VIN you entered is not included in the Set...
125,89603,2013,INTERNATIONAL,7400,1HTWGAAR4DJ131122,The VIN you entered is not included in the Set...
126,89613,2013,INTERNATIONAL,7400,1HTWGAAR6DJ131123,The VIN you entered is not included in the Set...
127,89623,2013,INTERNATIONAL,7400,1HTWGAAR8DJ131124,The VIN you entered is not included in the Set...
128,89633,2013,INTERNATIONAL,7400,1HTWJAAR3DJ166526,The VIN you entered is not included in the Set...
129,89643,2013,INTERNATIONAL,7400,1HTWJAAR3DJ131159,The VIN you entered is not included in the Set...
130,89653,2013,INTERNATIONAL,7400,1HTWGAAR5DJ131114,The VIN you entered is not included in the Set...
131,89663,2013,INTERNATIONAL,7400,1HTWGAAR7DJ131115,The VIN you entered is not included in the Set...
132,89673,2013,INTERNATIONAL,7400,1HTWGAAR9DJ131116,The VIN you entered is not included in the Set...
133,89683,2013,INTERNATIONAL,7400,1HTWGAAR0DJ131117,The VIN you entered is not included in the Set...
134,89693,2013,INTERNATIONAL,7400,1HTWJAAR5DJ131180,The VIN you entered is not included in the Set...
135,94004,2014,INTERNATIONAL,7400,1HTWGAAR5EH091206,The VIN you entered is not included in the Set...
136,96001,2011,INTERNATIONAL,7400,1HTWJAARXBJ383102,The VIN you entered is not included in the Set...
137,96003,2013,INTERNATIONAL,7400,1HTWGAARXDJ131321,The VIN you entered is not included in the Set...
138,96011,2011,INTERNATIONAL,7400,1HTWJAAR1BJ383103,The VIN you entered is not included in the Set...
139,96013,2013,INTERNATIONAL,7400,1HTWGAAR3DJ166492,The VIN you entered is not included in the Set...
140,96021,2012,INTERNATIONAL,7400,1HTWGAAR9CJ547228,The VIN you entered is not included in the Set...
141,97004,2014,INTERNATIONAL,7400,1HTWJAARXEJ468655,The VIN you entered is not included in the Set...
142,98002,2012,INTERNATIONAL,7400,1HTWGAAT3CJ547270,The VIN you entered is not included in the Set...
143,98032,2012,INTERNATIONAL,7400,1HTWGAAT4CJ547276,The VIN you entered is not included in the Set...
144,98042,2012,INTERNATIONAL,7400,1HTWGAAT9CJ547273,The VIN you entered is not included in the Set...
145,98052,2012,INTERNATIONAL,7400,1HTWGAAT8CJ547281,The VIN you entered is not included in the Set...
146,98062,2012,INTERNATIONAL,7400,1HTWGAAT8CJ699898,The VIN you entered is not included in the Set...
147,98072,2012,INTERNATIONAL,7400,1HTWGAATXCJ699899,The VIN you entered is not included in the Set...
148,99004,2014,INTERNATIONAL,7400,1HTWHAZR3EH768609,The VIN you entered is not included in the Set...
149,99822,2012,INTERNATIONAL,4300,1HTMMAAL3CH457396,The VIN you entered is not included in the Set...
150,Z77011,2011,INTERNATIONAL,7400,1HTWGAARXBJ383101,The VIN you entered is not included in the Set...
151,Z82001,2011,INTERNATIONAL,7300,1HTWBAAN5BJ383096,The VIN you entered is not included in the Set...

In [12]:
df['Response'].value_counts()

The VIN you entered is not included in the Settlement as a Class Vehicle.    152
Name: Response, dtype: int64

In [13]:
df.columns

Index(['TechIdentNo', 'ConstructYear', 'Manufacturer', 'Model number', 'VIN',
       'Response'],
      dtype='object')

In [14]:
df.to_excel(output_dir + fileName.split('.')[0] + ' with response.xlsx',index = False)