In [1]:
from Header_dict import header_dict
import pandas as pd
header_dict

{'01-17-2013 - Mattress Firm - Adhoc #50358.xlsx': {'CC': '15', 'Output': '1'},
 '01-17-2013 - Mattress Firm - Adhoc.xlsx': {'CC': '15', 'Output': '1'},
 '2.4.29 2.4.10_Debt Schedules_MLI (No APC Data).xlsx': {'PPEC': 'NO VIN or State',
  'PY': 'NO VIN or State',
  'Sheet1': 'NO VIN or State',
  '1 - Capital Lease RF': 'NO VIN or State',
  '2 - Note Payable RF': 'NO VIN or State'},
 '2014-15 Auto Schedule.xlsx': {'Update Form': '17',
  'Summary 08.01.14': '3',
  'Sheet2': 'Empty Sheet'},
 '2014Q2 Truck Inventory Update 2014-07-28.xlsx': {'Update Form': '17',
  'Summary 08.01.14': '3',
  'Sheet2': 'Empty Sheet'},
 'Auto Schedule as of 10.10.12.xls': {'Auto Schedule 11-12': '1',
  'Sheet2': '1'},
 'Auto Schedule as of 11.5.13. sent for renewal.xls': {'Update Form': '17',
  'P7 Update': '1'},
 'CHECKLIST FOR VEHICLE TRANSFERS.xlsx': {'Sheet1': '3',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.14.xlsx': {'Sheet1': '3',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx': {'Sheet1': '3',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Chicago Truck Information.xlsx': {'Sheet1': '6',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Copy of Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Copy of Q2-2013 Truck Inventory Update JK Revised.xlsx': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Copy of Researched Vehicle Data.xlsx': {'Sheet1': '1'},
 'HAA Status.xls': {'Sheet1': '5',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'MF List.xlsx': {'Sheet1': '12',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Mattress Firm Auto Parts Schedule.xlsx': {'Schedule of Vehicles': '1'},
 'Mattress Inc 2014 Final Vehicle List.xlsx': {'Sheet1': '2',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Mattress Liquidator Trucks.xls': {'MLI': '5'},
 'P1-2013 Truck Detail.xlsx': {'03.27.13': '3',
  '04.04.13': '3',
  'Brooks List': '1'},
 'P1-2013 Truck Inventory Update.xlsx': {'Sheet1': '15',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'P1-2013 Truck Inventory.xlsx': {'Sheet1': '15',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'P1-2013 Truck Moves.xlsx': {'03.27.13': '3',
  '04.04.13': '3',
  'Brooks List': '1'},
 'P1-2013 Trucks.xlsx': {'Sheet1': '15',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'P3-2013 Truck Inventory Update.xlsx': {'P3 2013 Summary': '6',
  'No Trucks': '17',
  'Albany': '15',
  'Atlanta': '15',
  'Bloomington': '15',
  'Charlotte': '15',
  'Charleston': '15',
  'Columbus': '15',
  'Davenport': '15',
  'Fayetteville': '15',
  'Greenville': '15',
  'Houston': '15',
  'Jacksonville': '15',
  'OKC': '15',
  'San Antonio': '15',
  'St Pete': '15',
  'Mebane': '15',
  'Miami North': '15',
  'Miami South': '15',
  'Phoenix': '15',
  'VB & Newport News': '15',
  'Whiteville': '15',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'P3-2013 Truck Inventory.xlsx': {'P3 2013 Summary': '6',
  'No Trucks': '17',
  'Albany': '15',
  'Atlanta': '15',
  'Bloomington': '15',
  'Charlotte': '15',
  'Charleston': '15',
  'Columbus': '15',
  'Davenport': '15',
  'Fayetteville': '15',
  'Greenville': '15',
  'Houston': '15',
  'Jacksonville': '15',
  'OKC': '15',
  'San Antonio': '15',
  'St Pete': '15',
  'Mebane': '15',
  'Miami North': '15',
  'Miami South': '15',
  'Phoenix': '15',
  'VB & Newport News': '15',
  'Whiteville': '15',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'P3-2013 Trucks.xlsx': {'P3 2013 Summary': '6',
  'No Trucks': '17',
  'Albany': '15',
  'Atlanta': '15',
  'Bloomington': '15',
  'Charlotte': '15',
  'Charleston': '15',
  'Columbus': '15',
  'Davenport': '15',
  'Fayetteville': '15',
  'Greenville': '15',
  'Houston': '15',
  'Jacksonville': '15',
  'OKC': '15',
  'San Antonio': '15',
  'St Pete': '15',
  'Mebane': '15',
  'Miami North': '15',
  'Miami South': '15',
  'Phoenix': '15',
  'VB & Newport News': '15',
  'Whiteville': '15',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'PD01-FY2014 Truck Inventory Update 043014.xlsx': {'Update Form': '17',
  'Updated 043014': '8',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Penske Lease List_032612.xls': {'December, 2010': 'NO VIN or State',
  'Status': '3',
  'Start of Year': '3',
  'March 2012': '1'},
 'Proj Hawk - Truck Requirements.xls': {'Sheet1': '6',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Q2-2013 Truck HAA 112213.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Truck Inventory HAA 112213.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Truck Inventory Update 081913 - 12 16 13.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Truck Inventory Update 081913.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Truck Inventory Update.xlsx': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami South 052099': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Portland 085000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Truck Inventory.xlsx': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'Q2-2013 Trucks.xls': {'Update Form': '17',
  'P7 Update': '8',
  'Check Off': '30',
  'Houston 001000': '17',
  'Atlanta 007000': '17',
  'Mebane 1300': '17',
  'Jacksonville 016000': '15',
  'Charlotte 024000': '17',
  'St. Petersburg 025000': '17',
  'Phoenix 02900': '17',
  'Columbia 033000': '17',
  'Columbus 037000': '17',
  'Greenville 038000': '17',
  'Charleston 040000': '17',
  'OKC 041000': '17',
  'Miami North 052000': '17',
  'Miami South 052099': '17',
  'Davenport 054000': '17',
  'Fayetteville 072000': '17',
  'Whiteville 076000': '17',
  'Pensacola 081000': '17',
  'Boise 082000': '17',
  'Portland 085000': '17',
  'Pocatello 089000': '17',
  'Spokane 101000': '17',
  'South Bend 102000': '17'},
 'VH Report for Kamal - F12 P11.xlsx': {'Sheet1': '8'},
 'Vehicle (073000) Details.xlsx': {'Sheet1': 'NO VIN or State',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Vehicle (073000).xlsx': {'Sheet1': 'NO VIN or State',
  'Sheet2': 'Empty Sheet',
  'Sheet3': 'Empty Sheet'},
 'Vehicle Inventory Spreadsheet 08 19 13.xls': {'Summary Page': '3',
  'Sheet1': 'NO VIN or State',
  'Addtl': '3'},
 'Vehicle Inventory Spreadsheet.xls': {'Summary Page': '3',
  'Sheet1': 'NO VIN or State'},
 'Vehicles Inventory Spreadsheet.xls': {'Summary Page': '3',
  'Sheet1': 'NO VIN or State'}}

In [19]:
list(header_dict.values())[0]
header_dict[list(header_dict.keys())[0]]
for a in header_dict:
    print(header_dict[a])

{'CC': '15', 'Output': '1'}
{'CC': '15', 'Output': '1'}
{'PPEC': 'NO VIN or State', 'PY': 'NO VIN or State', 'Sheet1': 'NO VIN or State', '1 - Capital Lease RF': 'NO VIN or State', '2 - Note Payable RF': 'NO VIN or State'}
{'Update Form': '17', 'Summary 08.01.14': '3', 'Sheet2': 'Empty Sheet'}
{'Update Form': '17', 'Summary 08.01.14': '3', 'Sheet2': 'Empty Sheet'}
{'Auto Schedule 11-12': '1', 'Sheet2': '1'}
{'Update Form': '17', 'P7 Update': '1'}
{'Sheet1': '3', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Sheet1': '3', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Sheet1': '3', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Sheet1': '6', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Sheet1': '1'}
{'Sheet1': '5', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Schedule of Vehicles': '1'}
{'Sheet1': '2', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'MLI': '5'}
{'Sheet1': '12', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'03.27.13': '3', '04.04.13': '3', 'Brooks List': '1'}
{'Sheet1': '15', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Sheet1': '15', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'03.27.13': '3', '04.04.13': '3', 'Brooks List': '1'}
{'Sheet1': '15', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'P3 2013 Summary': '6', 'No Trucks': '17', 'Albany': '15', 'Atlanta': '15', 'Bloomington': '15', 'Charlotte': '15', 'Charleston': '15', 'Columbus': '15', 'Davenport': '15', 'Fayetteville': '15', 'Greenville': '15', 'Houston': '15', 'Jacksonville': '15', 'OKC': '15', 'San Antonio': '15', 'St Pete': '15', 'Mebane': '15', 'Miami North': '15', 'Miami South': '15', 'Phoenix': '15', 'VB & Newport News': '15', 'Whiteville': '15', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'P3 2013 Summary': '6', 'No Trucks': '17', 'Albany': '15', 'Atlanta': '15', 'Bloomington': '15', 'Charlotte': '15', 'Charleston': '15', 'Columbus': '15', 'Davenport': '15', 'Fayetteville': '15', 'Greenville': '15', 'Houston': '15', 'Jacksonville': '15', 'OKC': '15', 'San Antonio': '15', 'St Pete': '15', 'Mebane': '15', 'Miami North': '15', 'Miami South': '15', 'Phoenix': '15', 'VB & Newport News': '15', 'Whiteville': '15', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'P3 2013 Summary': '6', 'No Trucks': '17', 'Albany': '15', 'Atlanta': '15', 'Bloomington': '15', 'Charlotte': '15', 'Charleston': '15', 'Columbus': '15', 'Davenport': '15', 'Fayetteville': '15', 'Greenville': '15', 'Houston': '15', 'Jacksonville': '15', 'OKC': '15', 'San Antonio': '15', 'St Pete': '15', 'Mebane': '15', 'Miami North': '15', 'Miami South': '15', 'Phoenix': '15', 'VB & Newport News': '15', 'Whiteville': '15', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Update Form': '17', 'Updated 043014': '8', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'December, 2010': 'NO VIN or State', 'Status': '3', 'Start of Year': '3', 'March 2012': '1'}
{'Sheet1': '6', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami South 052099': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Portland 085000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Update Form': '17', 'P7 Update': '8', 'Check Off': '30', 'Houston 001000': '17', 'Atlanta 007000': '17', 'Mebane 1300': '17', 'Jacksonville 016000': '15', 'Charlotte 024000': '17', 'St. Petersburg 025000': '17', 'Phoenix 02900': '17', 'Columbia 033000': '17', 'Columbus 037000': '17', 'Greenville 038000': '17', 'Charleston 040000': '17', 'OKC 041000': '17', 'Miami North 052000': '17', 'Miami South 052099': '17', 'Davenport 054000': '17', 'Fayetteville 072000': '17', 'Whiteville 076000': '17', 'Pensacola 081000': '17', 'Boise 082000': '17', 'Portland 085000': '17', 'Pocatello 089000': '17', 'Spokane 101000': '17', 'South Bend 102000': '17'}
{'Sheet1': 'NO VIN or State', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Sheet1': 'NO VIN or State', 'Sheet2': 'Empty Sheet', 'Sheet3': 'Empty Sheet'}
{'Summary Page': '3', 'Sheet1': 'NO VIN or State', 'Addtl': '3'}
{'Summary Page': '3', 'Sheet1': 'NO VIN or State'}
{'Summary Page': '3', 'Sheet1': 'NO VIN or State'}
{'Sheet1': '98'}

In [2]:
_ = r'C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Mattress Firm\Source\\'
Dict = {}
for file in header_dict:
    print(file)
    for i,sheet in enumerate(header_dict[file]):
        if header_dict[file][sheet] == 'NO VIN or State':
            df = pd.DataFrame({'FileName' :file, 'Index of Sheet':i+1,'SheetName': [str(sheet)],'row Contains Information':['NO']})
        elif header_dict[file][sheet] == 'Empty Sheet':
            df = pd.DataFrame({'FileName' :file, 'Index of Sheet':i+1,'SheetName': [str(sheet)],'row Contains Information':['Empty Sheet']})
        else:
            header = int(header_dict[file][sheet]) - 1
            df = pd.read_excel(_ + file,sheet_name=sheet,header = header)
            df = df.loc[:,df.columns.str.contains('state|vin|date|Auto ID Card Sent|In Service|pis|detailed',regex = True, case = False,na=False)]
            df.insert(0,'FileName',file)
            df.insert(1,'Index of Sheet',i+1)
            df.insert(2,'SheetName' ,sheet)
            df.insert(3,'row Contains Information','Yes')
            df.insert(4,'headerrow', header)
            df.insert(5,'number of record',len(df))
        if i == 0:
            Dict[file] = df
        else:
            Dict[file] = pd.concat([Dict[file],df],sort=False)

01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
01-17-2013 - Mattress Firm - Adhoc.xlsx
2.4.29 2.4.10_Debt Schedules_MLI (No APC Data).xlsx
2014-15 Auto Schedule.xlsx
2014Q2 Truck Inventory Update 2014-07-28.xlsx
Auto Schedule as of 10.10.12.xls
Auto Schedule as of 11.5.13. sent for renewal.xls
CHECKLIST FOR VEHICLE TRANSFERS.xlsx
CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.14.xlsx
CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx
Chicago Truck Information.xlsx
Copy of Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls
Copy of Q2-2013 Truck Inventory Update JK Revised.xlsx
Copy of Researched Vehicle Data.xlsx
HAA Status.xls
MF List.xlsx
Mattress Firm Auto Parts Schedule.xlsx
Mattress Inc 2014 Final Vehicle List.xlsx
Mattress Liquidator Trucks.xls
P1-2013 Truck Detail.xlsx
P1-2013 Truck Inventory Update.xlsx
P1-2013 Truck Inventory.xlsx
P1-2013 Truck Moves.xlsx
P1-2013 Trucks.xlsx
P3-2013 Truck Inventory Update.xlsx
P3-2013 Truck Inventory.xlsx
P3-2013 Trucks.xlsx
PD01-FY2014 Truck Inventory Update 043014.xlsx
Penske Lease List_032612.xls
Proj Hawk - Truck Requirements.xls
Q2-2013 Truck HAA 112213.xls
Q2-2013 Truck Inventory HAA 112213.xls
Q2-2013 Truck Inventory Update 081913 - 12 16 13.xls
Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls
Q2-2013 Truck Inventory Update 081913.xls
Q2-2013 Truck Inventory Update.xlsx
Q2-2013 Truck Inventory.xlsx
Q2-2013 Trucks.xls
VH Report for Kamal - F12 P11.xlsx
Vehicle (073000) Details.xlsx
Vehicle (073000).xlsx
Vehicle Inventory Spreadsheet 08 19 13.xls
Vehicle Inventory Spreadsheet.xls
Vehicles Inventory Spreadsheet.xls

In [3]:
result = pd.concat(Dict,sort=False)
# result.to_excel('C:\\Users\\FFR0103\\Desktop\\My files\\WORK\\Auto part\\Mattress Firm\\Output\\Result_with_date.xlsx')

## Check the date columns

In [4]:
for a in ['In Service'
,'Date Added to Insurance'
,'Auto ID Card Sent'
,'DATE ACQUIRED'
,'In Service'
,'Estimated Pick Up Date'
,'In Service Date'
,'Purchase Date'
,'Original In-Service Date'
,'PIS'] :
    print(a, a in result.columns)

In Service True
Date Added to Insurance True
Auto ID Card Sent True
DATE ACQUIRED True
In Service True
Estimated Pick Up Date True
In Service Date True
Purchase Date True
Original In-Service Date True
PIS True

## Find Feature

In [32]:
import pandas as pd
import glob
FileName = glob.glob('C:\\Users\\FFR0103\\Desktop\\My files\\WORK\\Auto part\\Mattress Firm\\Source\\*.*')
Dict = {}
for i,file in enumerate(FileName):
    print('#of file',i)
    DF = pd.read_excel(file,sheet_name=None, header=None, dtype=str)
    for i,sheet in enumerate(DF):
        if len(DF[sheet]) > 0:
            for row in range(len(DF[sheet])):                
                if DF[sheet].iloc[row, :].str.contains('pis',regex = True, case = False,na=False).sum()>0:
                    print(file, sheet)
                    break
                    
# Search history
# 86 CHEVY VAN FREDDY MALDO
# pis

#of file 0
#of file 1
#of file 2
#of file 3
#of file 4
#of file 5
#of file 6
#of file 7
#of file 8
#of file 9
#of file 10
#of file 11
#of file 12
#of file 13
#of file 14
#of file 15
#of file 16
#of file 17
#of file 18
#of file 19
#of file 20
#of file 21
#of file 22
#of file 23
#of file 24
#of file 25
#of file 26
#of file 27
#of file 28
#of file 29
#of file 30
#of file 31
#of file 32
#of file 33
#of file 34
#of file 35
#of file 36
#of file 37
#of file 38
C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Mattress Firm\Source\Vehicle (073000) Details.xlsx Sheet1
#of file 39
C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Mattress Firm\Source\Vehicle (073000).xlsx Sheet1
#of file 40
#of file 41
#of file 42
#of file 43
C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Mattress Firm\Source\VH Report for Kamal - F12 P11.xlsx Sheet1

# Clean up the Output

In [30]:
CL = pd.read_excel('C:\\Users\\FFR0103\\Desktop\\My files\\WORK\\Auto part\\Mattress Firm\\Output\\Result_with_date.xlsx', index_col = [0,1])
# CL[CL['row Contains Information'] =='No']
CL['row Contains Information'].value_counts()

Yes            3469
Empty Sheet      34
NO               11
Name: row Contains Information, dtype: int64

In [24]:
for i, col in enumerate(CL.columns):
    print (i, col)

0 FileName
1 Index of Sheet
2 SheetName
3 row Contains Information
4 headerrow
5 number of record
6 Vin
7 VIN #
8 Original In-Service Date
9 Contract Expiration Date
10 Schedule A Date
11 Lease Date
12 License Plate State
13 VIN No.
14 State
15 Registration Expiration Date
16 US DOT Expiration Date
17 Date Added to Insurance
18 Garaged State
19 Will this vehicle cross any state lines while traveling? If so, which ones?
20 Auto ID Card Sent
21 DATE ACQUIRED
22 STATE OF ISSUE
23 VIN # VERIFICATION
24 VIN#
25 NO TRUCKS - Moving OKC truck to here
26 In Service
27 2012 Tax Bill. VIN#1186 and 2378.pdf"
28 VIN
29 LEASE MATURITY DATE
30 Estimated Pick Up Date
31 State.1
32 In Service Date
33 States Traveled
34 License Plate Expiration Date
35 If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI?
36 PIS
37 Detailed Description
38 Purchase Date

##  Pick up the VIN columns

In [18]:
CL.iloc[:,23].unique()

array([nan, 'NOT REQ', 'REQUIRED'], dtype=object)

### selected VIN Columns

In [22]:
CL.columns[[6,7,13,24,28,37]]

Index(['Vin', 'VIN #', 'VIN No.', 'VIN#', 'VIN', 'Detailed Description'], dtype='object')

### Check other cols don't have the VIN

In [31]:
for a in [col for col in CL.columns if col not in CL.columns[[0,1,2,3,4,5,6,7,13,24,28,37]]]:
    print(a, CL[a].unique(),'\n\n\n\n\n\n')

Original In-Service Date [                          'NaT' '2007-08-10T00:00:00.000000000'
 '2012-04-10T00:00:00.000000000' '2012-04-16T00:00:00.000000000'
 '2012-04-12T00:00:00.000000000' '2007-06-27T00:00:00.000000000'
 '2007-09-26T00:00:00.000000000' '2007-07-06T00:00:00.000000000'
 '2007-07-12T00:00:00.000000000' '2006-01-27T00:00:00.000000000']






Contract Expiration Date [                          'NaT' '2015-08-31T00:00:00.000000000'
 '2020-04-30T00:00:00.000000000' '2015-06-30T00:00:00.000000000'
 '2016-09-30T00:00:00.000000000' '2015-07-31T00:00:00.000000000'
 '2012-01-31T00:00:00.000000000']






Schedule A Date [                          'NaT' '2006-09-27T00:00:00.000000000'
 '2011-12-22T00:00:00.000000000' '2007-09-18T00:00:00.000000000'
 '2005-07-20T00:00:00.000000000']






Lease Date [                          'NaT' '2003-10-20T00:00:00.000000000'
 '2002-11-01T00:00:00.000000000']






License Plate State [nan 'FL' 'TX' '  ' 'NV' 'MN' 'DE' 'GA' 'MA' 'NH' 'PA']






State [nan 'TX' 'CO' 'GA' 'NC' 'FL' 'OK' 'AZ' 'SC' 'IN' 'NV' 'VA' 'OR' 'WA' 'AR'
 'AL' 'ID' 'HI' 'NY' 'MI' 'OH' 'PA' 'IL' 'UT' 'KS' 'TN' 'CA' 'WI' ' NY'
 ' NJ' ' MD' ' MA' ' CT' ' FL' ' CA' 'NJ']






Registration Expiration Date [                          'NaT' '2014-07-01T00:00:00.000000000'
 '2014-09-01T00:00:00.000000000' '2013-10-01T00:00:00.000000000'
 '2013-07-01T00:00:00.000000000' '2008-11-01T00:00:00.000000000'
 '2013-09-01T00:00:00.000000000' '2013-11-01T00:00:00.000000000']






US DOT Expiration Date [nan 'Y' 'N' 'y' 'n' 'Atlanta']






Date Added to Insurance [nan datetime.datetime(2013, 10, 31, 0, 0) 'Y' 'y' 'DC']






Garaged State [nan 'AR' 'AZ' 'FL' 'GA' 'IL' 'NC' 'NV' 'OH' 'SC' 'TX' 'VA']






Will this vehicle cross any state lines while traveling? If so, which ones? [nan 'washingington cnty' 'Emailed Justin Cassell 10/26 for missing info'
 'Mattress Xpress - need more info on location contact person'
 '9/11/12 asked Corinna for plate number' 'Inter-State (OH/IN/PN)']






Auto ID Card Sent [                          'NaT' '2012-10-30T00:00:00.000000000']






DATE ACQUIRED [                          'NaT' '2014-09-29T00:00:00.000000000']






STATE OF ISSUE [nan 'IL']






VIN # VERIFICATION [nan 'NOT REQ' 'REQUIRED']






NO TRUCKS - Moving OKC truck to here [nan 'NO TRUCKS' 'Included with VB' 'NEED INFO - FILE WAS CORRUPT'
 'NEED FILE INSTEAD OF EMAIL PICTURE']






In Service [nan 'Feb 16 2007' 'Jan 24 2007' 'Feb 2 2007' 'Mar 30 2007' 'Sept 1 2000'
 'Mar 31 2001' 'April 1 2007' datetime.datetime(2016, 10, 5, 0, 0)
 datetime.datetime(2018, 5, 30, 0, 0)]






2012 Tax Bill. VIN#1186 and 2378.pdf" [nan '2012 Veh Tax Bill. VIN#1186 and 2378.pdf"'
 '2014-15 Auto Schedule.xlsx"'
 '2014Q2 Truck Inventory Update 2014-07-28.xlsx"' '20140109154406115.pdf"'
 '20140109154437503.pdf"' '20140123113558664.pdf"'
 '20140606115234642.pdf"' '20141205095115685.pdf"'
 '20151105084108731.pdf"'
 'Abilene Truck Status - Acquired from Mattress Source.msg"'
 'Additional Title Transfer Info Needed.msg"'
 'Additional Truck Info Needed - Due_ Noon 05_02_2013.msg"'
 'April 25, 2014.pdf"' 'AR Renewal JNAMB80H05AN50271 011314.pdf"'
 'Atlanta GA 7000 -1995 Ford TK.pdf"' 'Auto Schedule as of 10.10.12.xls"'
 'Auto Schedule as of 11.5.13. sent for renewal.xls"'
 'Boise ID 82000 Insp.pdf"' 'Boise truck[1].pdf"'
 'Central ID 89000 Insp.pdf"' 'CHECKLIST FOR VEHICLE TRANSFERS.xlsx"'
 'CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.14.xlsx"'
 'CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx"'
 'Chicago Truck Information.xlsx"'
 'Copy of Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls"'
 'Copy of Q2-2013 Truck Inventory Update JK Revised.xlsx"'
 'Copy of Researched Vehicle Data.xlsx"' 'Ford 1.docx"' 'Ford 2.docx"'
 'FW_ #76000 Carolina Coast Truck.msg"'
 'FW_ _Important_  Mattress Firm Truck - Columbus (174).msg"'
 'FW_ OBX Truck.msg"'
 'FW_ Old 53 foot Trailer parked outside warehouse_.msg"'
 'FW_ Please take a look (151).msg"'
 'FW_ Purchase of mattress source pick up truck.msg"'
 'FW_ Titles and BOS - Greenville_ SC.msg"'
 'FW_ Truck title help - Pittsburgh.msg"'
 'FW_ Vehicle Citation (153).msg"' 'Fw_ Vehicle Information (155).msg"'
 'FW_ VIN # for truck.msg"' 'FW_ W_ Texas trucks (189).msg"'
 'Fwd_ Truck status.msg"' 'Fwd_ Trucks with expired tags.msg"'
 'Fwd_ Vehicle Information.msg"' 'HAA Invoice 1204.pdf"'
 'HAA Invoice 1207.pdf"' 'HAA Invoice 1215.pdf"' 'HAA Invoice 1216.pdf"'
 'HAA Status.xls"' 'Hino.docx"' 'IN inspection form 39530.pdf"'
 'Maine.pdf"' 'Maine0001.pdf"' 'Mattress Firm Auto Parts Schedule.xlsx"'
 'Mattress Inc 2014 Final Vehicle List.xlsx"'
 'Mattress Liquidator Trucks.xls"'
 'Mattress World aka Steelers Truck Titles.pdf"' 'Mebane trucks.pdf"'
 'Mf tax.pdf"'
 'MFI_Hawks_Schedules to Asset Purchase Agreement_Vehicles.pdf"'
 'Northern IN 102000 Insp.pdf"' 'Ohio Vehicle Verification.pdf"'
 'P1-2013 Truck Detail.xlsx"' 'P1-2013 Truck Inventory Update.xlsx"'
 'P1-2013 Truck Inventory.xlsx"' 'P1-2013 Truck Moves.xlsx"'
 'P1-2013 Trucks.xlsx"' 'P3-2013 Truck Inventory Update.xlsx"'
 'P3-2013 Truck Inventory.xlsx"' 'P3-2013 Trucks.xlsx"'
 'PD01-FY2014 Truck Inventory Update 043014.xlsx"'
 'Penske Lease List_032612.xls"' 'Phoenix Titles.msg"'
 'Proj Hawk - Truck Requirements.xls"' 'Q2-2013 Truck HAA 112213.xls"'
 'Q2-2013 Truck Inventory HAA 112213.xls"'
 'Q2-2013 Truck Inventory Update 081913 - 12 16 13.xls"'
 'Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls"'
 'Q2-2013 Truck Inventory Update 081913.xls"'
 'Q2-2013 Truck Inventory Update.xlsx"' 'Q2-2013 Truck Inventory.xlsx"'
 'Q2-2013 Trucks.xls"' 'Re_ #76000 Carolina Coast Truck (95).msg"'
 'RE_ 2 HINO TRUCK REGISTRATIONS.msg"'
 'RE_ Abilene Truck Status - Acquired from Mattress Source.msg"'
 'Re_ FW_ Truck title help - Pittsburgh.msg"' 'RE_ Greenville F150s.msg"'
 'RE_ Jax Whse Truck Title (90).msg"'
 'RE_ Mattress Firm - Truck Status (163).msg"'
 'RE_ Mattress Firm Vehicle Titles.msg"'
 'RE_ Mattress Liquidators - Second Amendment to TSA (44).msg"'
 'RE_ Miami Trucks- Need Titles changed to register.msg"'
 'RE_ MK Trucks (75).msg"'
 'RE_ Old 53 foot Trailer parked outside warehouse_ (113).msg"'
 'Re_ Please take a look (149).msg"'
 'Re_ Purchase of mattress source pick up truck (121).msg"'
 'RE_ REGISTRATION (115).msg"' 'RE_ Titles and BOS - Greenville_ SC.msg"'
 'RE_ Truck (103).msg"' 'RE_ Truck For Sale (73).msg"'
 'RE_ Truck for Sale.msg"' 'RE_ Truck in West TX (26).msg"'
 'RE_ Truck Mileage - Newly Acquired Truck (72).msg"'
 'RE_ Truck Purchase  (140).msg"' 'RE_ Trucks - Status (53).msg"'
 'RE_ Trucks with expired tags.msg"' 'RE_ Vehicle Citation.msg"'
 'RE_ W_ Texas trucks.msg"' 'Reg. Vin#0178.pdf"'
 'Scanned Truck Titles 11.03.14.pdf"' 'tix.pdf"' 'truck Data.pdf"'
 'Truck Info.pdf"' 'Truck inspection 2013.pdf"' 'Trucks Info.pdf"'
 'trucks.pdf"' 'Vehicle (073000) Details.xlsx"' 'Vehicle (073000).xlsx"'
 'Vehicle Citation.pdf"' 'Vehicle Inventory Spreadsheet 08 19 13.xls"'
 'Vehicle Inventory Spreadsheet.xls"' 'Vehicle Titles Received.pdf"'
 'Vehicles Inventory Spreadsheet.xls"'
 'VH Report for Kamal - F12 P11.xlsx"'
 '01-17-2013 - Mattress Firm - Adhoc #50358.xlsx"'
 '01-17-2013 - Mattress Firm - Adhoc.xlsx"']






LEASE MATURITY DATE [                          'NaT' '2014-09-29T00:00:00.000000000'
 '2014-08-30T00:00:00.000000000' '2015-05-25T00:00:00.000000000'
 '2016-10-17T00:00:00.000000000']






Estimated Pick Up Date [nan datetime.datetime(2013, 4, 2, 0, 0) 'ASAP'
 datetime.datetime(2013, 4, 10, 0, 0)]






State.1 [nan 'WA' 'ME' 'ID' 'AZ' 'TX']






In Service Date [nan datetime.datetime(2004, 4, 1, 0, 0)
 datetime.datetime(2004, 4, 8, 0, 0) datetime.datetime(2004, 4, 15, 0, 0)
 datetime.datetime(2004, 4, 21, 0, 0) datetime.datetime(2007, 7, 6, 0, 0)
 datetime.datetime(2007, 7, 12, 0, 0) datetime.datetime(2007, 8, 10, 0, 0)
 datetime.datetime(2004, 3, 22, 0, 0) datetime.datetime(2004, 4, 5, 0, 0)
 datetime.datetime(2004, 4, 6, 0, 0) 'Replaced 422147, 604700 returned'
 'Replaced 422144' 'Replaced 422146' datetime.datetime(2004, 3, 31, 0, 0)
 datetime.datetime(2004, 4, 14, 0, 0) datetime.datetime(2007, 6, 27, 0, 0)
 datetime.datetime(2007, 9, 26, 0, 0)]






States Traveled [nan 'Florida' 'Texas']






License Plate Expiration Date [nan]






If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI? [nan]






PIS [                          'NaT' '1998-01-12T00:00:00.000000000'
 '2000-09-13T00:00:00.000000000' '2000-10-25T00:00:00.000000000'
 '2000-12-22T00:00:00.000000000' '2001-11-26T00:00:00.000000000'
 '2000-02-15T00:00:00.000000000' '2001-12-15T00:00:00.000000000'
 '2000-02-23T00:00:00.000000000' '2000-04-30T00:00:00.000000000'
 '2001-06-01T00:00:00.000000000' '1998-05-21T00:00:00.000000000'
 '1998-02-25T00:00:00.000000000' '2000-05-15T00:00:00.000000000'
 '2000-05-26T00:00:00.000000000' '2000-03-31T00:00:00.000000000'
 '2001-06-30T00:00:00.000000000' '2001-04-17T00:00:00.000000000'
 '1997-01-15T00:00:00.000000000' '1998-02-28T00:00:00.000000000'
 '2000-04-05T00:00:00.000000000' '2000-08-19T00:00:00.000000000'
 '2000-09-18T00:00:00.000000000' '2000-10-16T00:00:00.000000000'
 '2000-11-14T00:00:00.000000000' '2000-02-29T00:00:00.000000000'
 '2002-03-03T00:00:00.000000000' '2002-03-30T00:00:00.000000000'
 '2002-04-15T00:00:00.000000000' '2002-04-30T00:00:00.000000000'
 '2002-05-22T00:00:00.000000000' '2002-05-28T00:00:00.000000000'
 '2002-06-27T00:00:00.000000000' '2002-12-31T00:00:00.000000000'
 '2003-04-23T00:00:00.000000000' '2003-05-27T00:00:00.000000000'
 '2003-06-17T00:00:00.000000000' '2003-10-28T00:00:00.000000000'
 '2004-05-04T00:00:00.000000000' '2004-05-19T00:00:00.000000000'
 '2004-05-26T00:00:00.000000000' '2004-05-27T00:00:00.000000000'
 '2004-06-01T00:00:00.000000000' '2004-06-30T00:00:00.000000000'
 '2004-06-18T00:00:00.000000000' '2004-07-05T00:00:00.000000000'
 '2004-06-14T00:00:00.000000000' '2004-07-22T00:00:00.000000000'
 '2004-07-30T00:00:00.000000000' '2004-08-30T00:00:00.000000000'
 '2004-09-13T00:00:00.000000000' '2004-09-14T00:00:00.000000000'
 '2004-11-02T00:00:00.000000000' '2004-12-15T00:00:00.000000000'
 '2005-01-03T00:00:00.000000000' '2005-01-27T00:00:00.000000000'
 '2005-01-31T00:00:00.000000000' '2005-04-12T00:00:00.000000000'
 '2005-05-31T00:00:00.000000000' '2005-06-27T00:00:00.000000000'
 '2006-06-21T00:00:00.000000000' '2006-11-28T00:00:00.000000000'
 '2006-11-29T00:00:00.000000000' '2007-02-27T00:00:00.000000000'
 '2007-05-21T00:00:00.000000000' '2007-12-17T00:00:00.000000000'
 '2007-11-28T00:00:00.000000000' '2007-06-06T00:00:00.000000000'
 '2007-10-23T00:00:00.000000000' '2010-12-01T00:00:00.000000000'
 '2005-02-28T00:00:00.000000000' '2004-12-31T00:00:00.000000000'
 '2004-08-31T00:00:00.000000000' '2007-05-29T00:00:00.000000000'
 '2012-09-25T00:00:00.000000000']






Purchase Date [                          'NaT' '2012-12-11T00:00:00.000000000']

### Clean VIN

In [6]:
df = pd.read_excel('C:\\Users\\FFR0103\\Desktop\\My files\\WORK\\Auto part\\Mattress Firm\\Output\\Result_with_date.xlsx', index_col = [0,1])


StandardVIN = pd.Series(None,index = range(len(df)))

df['# of  Value from selected VIN columns']=6-df[df.columns[[6,7,13,24,28,37]]].isnull().sum(axis = 1)

display(df['# of  Value from selected VIN columns'].value_counts())

for i in range(len(df)):
    temp = []
    for val in df.iloc[i,[6,7,13,24,28,37]]:
        if not pd.isnull(val):
            temp.append(str(val))
            StandardVIN[i] = ';'.join(temp)
StandardVIN

1    2463
0    1025
2      26
Name: # of  Value from selected VIN columns, dtype: int64

0        Unit Usage (Power, etc.);Usage (Power /Reefer)
1              In-Service Date;Original In-Service Date
2              Expiration Date;Contract Expiration Date
3                      Schedule "A" Number;Schedule A #
4                     Schedule "A" Date;Schedule A Date
5                                 Lease Type;Lease Type
6                              VLSA/VMA Date;Lease Date
7               Current Fixed Charge;Current Fixed Rate
8           Current Mileage Charge;Current Mileage Rate
9          Current Mileage Reading;Last Mileage Reading
10         Current License Plate Number;License Plate #
11      Current License Plate State;License Plate State
12      Gross Vehicle Weight;Vehicle Mfr's Gross Weight
13                                    1FVACWCS77DZ23370
14                                    1FVACWDT9CHBP3080
15                                    1FVACWDT0CHBP3081
16                                    1FVACWDT2CHBP3082
17                                    1FVACWCS97DZ23368
18                                    1FVACWDT4CHBP3083
19                                    1FVACWDT6CHBP3084
20
21                                    1FVACWCS07DZ23369
22                                    1FVACWCS97DZ23371
23                                    1FVACWDT8CHBP3085
24                                    1HTMMAAL96H319768
25       Unit Usage (Power, etc.);Usage (Power /Reefer)
26             In-Service Date;Original In-Service Date
27             Expiration Date;Contract Expiration Date
28                     Schedule "A" Number;Schedule A #
29                    Schedule "A" Date;Schedule A Date
                             ...
3484                                  JL6AAG1S98K010625
3485                                  JL6DGM1E27K009948
3486                                  JL6DGP1E37K015680
3487                                  JL6BBG1S7AK009528
3488                                  1FVACWDR8CHBC9891
3489                                                NaN
3490                                  1FTDF15Y6RNA32665
3491                                  IFTDF15475NA80178
3492                                  1FTZF1723XNC27926
3493                                  1FTZF1720YNC03570
3494                                  1FTZF17211NB33549
3495                                  1FTRX17W42NB61203
3496                                  JALB4B1AXRT008206
3497                                  1FTRF17253NB95913
3498                                  1FTRF17W23NA12115
3499                                   1FTRF17W8NA93363
3500                                  2FTRF17W53CA95626
3501                                 JL6AAF1H34KO011164
3502                                  JL6BBG1S16K011248
3503                                  JL6BBG1S96K007545
3504                                  JL6BBG1S46K007615
3505                                  JL6BBG1567K010890
3506                                  JL6BBG1S07K002378
3507                                  JL6BBG1S37K001869
3508                                  JL6AAG1S98K010625
3509                                  JL6DGM1E27K009948
3510                                  JL6DGP1E37K015680
3511                                  JL6BBG1S7AK009528
3512                                  1FVACWDR8CHBC9891
3513                                                NaN
Length: 3514, dtype: object

In [31]:
df[df['# of  Value from selected VIN columns'] == 0].iloc[:,[0,1,2,3,4,5,6,7,13,24,28,37]]

                                                                                                 FileName  \
2.4.29 2.4.10_Debt Schedules_MLI (No APC Data).... 0    2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...
                                                   0    2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...
                                                   0    2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...
                                                   0    2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...
                                                   0    2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...
2014-15 Auto Schedule.xlsx                         57                          2014-15 Auto Schedule.xlsx
                                                   58                          2014-15 Auto Schedule.xlsx
                                                   78                          2014-15 Auto Schedule.xlsx
                                                   79                          2014-15 Auto Schedule.xlsx
                                                   80                          2014-15 Auto Schedule.xlsx
                                                   81                          2014-15 Auto Schedule.xlsx
                                                   82                          2014-15 Auto Schedule.xlsx
                                                   83                          2014-15 Auto Schedule.xlsx
                                                   84                          2014-15 Auto Schedule.xlsx
                                                   85                          2014-15 Auto Schedule.xlsx
                                                   86                          2014-15 Auto Schedule.xlsx
                                                   87                          2014-15 Auto Schedule.xlsx
                                                   88                          2014-15 Auto Schedule.xlsx
                                                   89                          2014-15 Auto Schedule.xlsx
                                                   90                          2014-15 Auto Schedule.xlsx
                                                   91                          2014-15 Auto Schedule.xlsx
                                                   92                          2014-15 Auto Schedule.xlsx
                                                   93                          2014-15 Auto Schedule.xlsx
                                                   94                          2014-15 Auto Schedule.xlsx
                                                   95                          2014-15 Auto Schedule.xlsx
                                                   96                          2014-15 Auto Schedule.xlsx
                                                   97                          2014-15 Auto Schedule.xlsx
                                                   0                           2014-15 Auto Schedule.xlsx
2014Q2 Truck Inventory Update 2014-07-28.xlsx      57       2014Q2 Truck Inventory Update 2014-07-28.xlsx
                                                   58       2014Q2 Truck Inventory Update 2014-07-28.xlsx
...                                                                                                   ...
VH Report for Kamal - F12 P11.xlsx                 128                 VH Report for Kamal - F12 P11.xlsx
                                                   132                 VH Report for Kamal - F12 P11.xlsx
                                                   133                 VH Report for Kamal - F12 P11.xlsx
                                                   134                 VH Report for Kamal - F12 P11.xlsx
                                                   138                 VH Report for Kamal - F12 P11.xlsx
                                                   139                 VH Report for Kamal - F12 P11.xlsx
                                                   140                 VH Report for Kamal - F12 P11.xlsx
                                                   141                 VH Report for Kamal - F12 P11.xlsx
                                                   142                 VH Report for Kamal - F12 P11.xlsx
                                                   143                 VH Report for Kamal - F12 P11.xlsx
                                                   144                 VH Report for Kamal - F12 P11.xlsx
                                                   145                 VH Report for Kamal - F12 P11.xlsx
                                                   149                 VH Report for Kamal - F12 P11.xlsx
                                                   150                 VH Report for Kamal - F12 P11.xlsx
                                                   151                 VH Report for Kamal - F12 P11.xlsx
                                                   152                 VH Report for Kamal - F12 P11.xlsx
                                                   153                 VH Report for Kamal - F12 P11.xlsx
                                                   154                 VH Report for Kamal - F12 P11.xlsx
                                                   155                 VH Report for Kamal - F12 P11.xlsx
                                                   156                 VH Report for Kamal - F12 P11.xlsx
Vehicle (073000) Details.xlsx                      0                        Vehicle (073000) Details.xlsx
                                                   0                        Vehicle (073000) Details.xlsx
                                                   0                        Vehicle (073000) Details.xlsx
Vehicle (073000).xlsx                              0                                Vehicle (073000).xlsx
                                                   0                                Vehicle (073000).xlsx
                                                   0                                Vehicle (073000).xlsx
Vehicle Inventory Spreadsheet 08 19 13.xls         20          Vehicle Inventory Spreadsheet 08 19 13.xls
                                                   0           Vehicle Inventory Spreadsheet 08 19 13.xls
Vehicle Inventory Spreadsheet.xls                  0                    Vehicle Inventory Spreadsheet.xls
Vehicles Inventory Spreadsheet.xls                 0                   Vehicles Inventory Spreadsheet.xls

                                                        Index of Sheet  \
2.4.29 2.4.10_Debt Schedules_MLI (No APC Data).... 0                 1
                                                   0                 2
                                                   0                 3
                                                   0                 4
                                                   0                 5
2014-15 Auto Schedule.xlsx                         57                2
                                                   58                2
                                                   78                2
                                                   79                2
                                                   80                2
                                                   81                2
                                                   82                2
                                                   83                2
                                                   84                2
                                                   85                2
                                                   86                2
                                                   87                2
                                                   88                2
                                                   89                2
                                                   90                2
                                                   91                2
                                                   92                2
                                                   93                2
                                                   94                2
                                                   95                2
                                                   96                2
                                                   97                2
                                                   0                 3
2014Q2 Truck Inventory Update 2014-07-28.xlsx      57                2
                                                   58                2
...                                                                ...
VH Report for Kamal - F12 P11.xlsx                 128               1
                                                   132               1
                                                   133               1
                                                   134               1
                                                   138               1
                                                   139               1
                                                   140               1
                                                   141               1
                                                   142               1
                                                   143               1
                                                   144               1
                                                   145               1
                                                   149               1
                                                   150               1
                                                   151               1
                                                   152               1
                                                   153               1
                                                   154               1
                                                   155               1
                                                   156               1
Vehicle (073000) Details.xlsx                      0                 1
                                                   0                 2
                                                   0                 3
Vehicle (073000).xlsx                              0                 1
                                                   0                 2
                                                   0                 3
Vehicle Inventory Spreadsheet 08 19 13.xls         20                1
                                                   0                 2
Vehicle Inventory Spreadsheet.xls                  0                 2
Vehicles Inventory Spreadsheet.xls                 0                 2

                                                                   SheetName  \
2.4.29 2.4.10_Debt Schedules_MLI (No APC Data).... 0                    PPEC
                                                   0                      PY
                                                   0                  Sheet1
                                                   0    1 - Capital Lease RF
                                                   0     2 - Note Payable RF
2014-15 Auto Schedule.xlsx                         57       Summary 08.01.14
                                                   58       Summary 08.01.14
                                                   78       Summary 08.01.14
                                                   79       Summary 08.01.14
                                                   80       Summary 08.01.14
                                                   81       Summary 08.01.14
                                                   82       Summary 08.01.14
                                                   83       Summary 08.01.14
                                                   84       Summary 08.01.14
                                                   85       Summary 08.01.14
                                                   86       Summary 08.01.14
                                                   87       Summary 08.01.14
                                                   88       Summary 08.01.14
                                                   89       Summary 08.01.14
                                                   90       Summary 08.01.14
                                                   91       Summary 08.01.14
                                                   92       Summary 08.01.14
                                                   93       Summary 08.01.14
                                                   94       Summary 08.01.14
                                                   95       Summary 08.01.14
                                                   96       Summary 08.01.14
                                                   97       Summary 08.01.14
                                                   0                  Sheet2
2014Q2 Truck Inventory Update 2014-07-28.xlsx      57       Summary 08.01.14
                                                   58       Summary 08.01.14
...                                                                      ...
VH Report for Kamal - F12 P11.xlsx                 128                Sheet1
                                                   132                Sheet1
                                                   133                Sheet1
                                                   134                Sheet1
                                                   138                Sheet1
                                                   139                Sheet1
                                                   140                Sheet1
                                                   141                Sheet1
                                                   142                Sheet1
                                                   143                Sheet1
                                                   144                Sheet1
                                                   145                Sheet1
                                                   149                Sheet1
                                                   150                Sheet1
                                                   151                Sheet1
                                                   152                Sheet1
                                                   153                Sheet1
                                                   154                Sheet1
                                                   155                Sheet1
                                                   156                Sheet1
Vehicle (073000) Details.xlsx                      0                  Sheet1
                                                   0                  Sheet2
                                                   0                  Sheet3
Vehicle (073000).xlsx                              0                  Sheet1
                                                   0                  Sheet2
                                                   0                  Sheet3
Vehicle Inventory Spreadsheet 08 19 13.xls         20           Summary Page
                                                   0                  Sheet1
Vehicle Inventory Spreadsheet.xls                  0                  Sheet1
Vehicles Inventory Spreadsheet.xls                 0                  Sheet1

                                                       row Contains Information  \
2.4.29 2.4.10_Debt Schedules_MLI (No APC Data).... 0                         NO
                                                   0                         NO
                                                   0                         NO
                                                   0                         NO
                                                   0                         NO
2014-15 Auto Schedule.xlsx                         57                       Yes
                                                   58                       Yes
                                                   78                       Yes
                                                   79                       Yes
                                                   80                       Yes
                                                   81                       Yes
                                                   82                       Yes
                                                   83                       Yes
                                                   84                       Yes
                                                   85                       Yes
                                                   86                       Yes
                                                   87                       Yes
                                                   88                       Yes
                                                   89                       Yes
                                                   90                       Yes
                                                   91                       Yes
                                                   92                       Yes
                                                   93                       Yes
                                                   94                       Yes
                                                   95                       Yes
                                                   96                       Yes
                                                   97                       Yes
                                                   0                Empty Sheet
2014Q2 Truck Inventory Update 2014-07-28.xlsx      57                       Yes
                                                   58                       Yes
...                                                                         ...
VH Report for Kamal - F12 P11.xlsx                 128                      Yes
                                                   132                      Yes
                                                   133                      Yes
                                                   134                      Yes
                                                   138                      Yes
                                                   139                      Yes
                                                   140                      Yes
                                                   141                      Yes
                                                   142                      Yes
                                                   143                      Yes
                                                   144                      Yes
                                                   145                      Yes
                                                   149                      Yes
                                                   150                      Yes
                                                   151                      Yes
                                                   152                      Yes
                                                   153                      Yes
                                                   154                      Yes
                                                   155                      Yes
                                                   156                      Yes

## Pick up the state Columns

In [33]:
for i, col in enumerate(CL.columns):
    print (i, col)

0 FileName
1 Index of Sheet
2 SheetName
3 row Contains Information
4 headerrow
5 number of record
6 Vin
7 VIN #
8 Original In-Service Date
9 Contract Expiration Date
10 Schedule A Date
11 Lease Date
12 License Plate State
13 VIN No.
14 State
15 Registration Expiration Date
16 US DOT Expiration Date
17 Date Added to Insurance
18 Garaged State
19 Will this vehicle cross any state lines while traveling? If so, which ones?
20 Auto ID Card Sent
21 DATE ACQUIRED
22 STATE OF ISSUE
23 VIN # VERIFICATION
24 VIN#
25 NO TRUCKS - Moving OKC truck to here
26 In Service
27 2012 Tax Bill. VIN#1186 and 2378.pdf"
28 VIN
29 LEASE MATURITY DATE
30 Estimated Pick Up Date
31 State.1
32 In Service Date
33 States Traveled
34 License Plate Expiration Date
35 If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI?
36 PIS
37 Detailed Description
38 Purchase Date

### Selected State columns

In [34]:
CL.iloc[:,19].unique()

array([nan, 'washingington cnty',
       'Emailed Justin Cassell 10/26 for missing info',
       'Mattress Xpress - need more info on location contact person',
       '9/11/12 asked Corinna for plate number', 'Inter-State (OH/IN/PN)'],
      dtype=object)

In [35]:
CL.iloc[:,22].unique()

array([nan, 'IL'], dtype=object)

In [36]:
CL.iloc[:,33].unique()

array([nan, 'Florida', 'Texas'], dtype=object)

In [38]:
CL.iloc[:,35].unique()

array([nan])

In [37]:
CL.columns[[12,14,18,22,31,33]]

Index(['License Plate State', 'State', 'Garaged State', 'STATE OF ISSUE',
       'State.1', 'States Traveled'],
      dtype='object')

### check the rest of cols don't contains state.

In [39]:
for a in [col for col in CL.columns if col not in CL.columns[[0,1,2,3,4,5,6,7,13,24,28,37,12,14,18,22,31,33]]]:
    print(a, CL[a].unique(),'\n\n\n\n\n\n')

Original In-Service Date [                          'NaT' '2007-08-10T00:00:00.000000000'
 '2012-04-10T00:00:00.000000000' '2012-04-16T00:00:00.000000000'
 '2012-04-12T00:00:00.000000000' '2007-06-27T00:00:00.000000000'
 '2007-09-26T00:00:00.000000000' '2007-07-06T00:00:00.000000000'
 '2007-07-12T00:00:00.000000000' '2006-01-27T00:00:00.000000000']






Contract Expiration Date [                          'NaT' '2015-08-31T00:00:00.000000000'
 '2020-04-30T00:00:00.000000000' '2015-06-30T00:00:00.000000000'
 '2016-09-30T00:00:00.000000000' '2015-07-31T00:00:00.000000000'
 '2012-01-31T00:00:00.000000000']






Schedule A Date [                          'NaT' '2006-09-27T00:00:00.000000000'
 '2011-12-22T00:00:00.000000000' '2007-09-18T00:00:00.000000000'
 '2005-07-20T00:00:00.000000000']






Lease Date [                          'NaT' '2003-10-20T00:00:00.000000000'
 '2002-11-01T00:00:00.000000000']






Registration Expiration Date [                          'NaT' '2014-07-01T00:00:00.000000000'
 '2014-09-01T00:00:00.000000000' '2013-10-01T00:00:00.000000000'
 '2013-07-01T00:00:00.000000000' '2008-11-01T00:00:00.000000000'
 '2013-09-01T00:00:00.000000000' '2013-11-01T00:00:00.000000000']






US DOT Expiration Date [nan 'Y' 'N' 'y' 'n' 'Atlanta']






Date Added to Insurance [nan datetime.datetime(2013, 10, 31, 0, 0) 'Y' 'y' 'DC']






Will this vehicle cross any state lines while traveling? If so, which ones? [nan 'washingington cnty' 'Emailed Justin Cassell 10/26 for missing info'
 'Mattress Xpress - need more info on location contact person'
 '9/11/12 asked Corinna for plate number' 'Inter-State (OH/IN/PN)']






Auto ID Card Sent [                          'NaT' '2012-10-30T00:00:00.000000000']






DATE ACQUIRED [                          'NaT' '2014-09-29T00:00:00.000000000']






VIN # VERIFICATION [nan 'NOT REQ' 'REQUIRED']






NO TRUCKS - Moving OKC truck to here [nan 'NO TRUCKS' 'Included with VB' 'NEED INFO - FILE WAS CORRUPT'
 'NEED FILE INSTEAD OF EMAIL PICTURE']






In Service [nan 'Feb 16 2007' 'Jan 24 2007' 'Feb 2 2007' 'Mar 30 2007' 'Sept 1 2000'
 'Mar 31 2001' 'April 1 2007' datetime.datetime(2016, 10, 5, 0, 0)
 datetime.datetime(2018, 5, 30, 0, 0)]






2012 Tax Bill. VIN#1186 and 2378.pdf" [nan '2012 Veh Tax Bill. VIN#1186 and 2378.pdf"'
 '2014-15 Auto Schedule.xlsx"'
 '2014Q2 Truck Inventory Update 2014-07-28.xlsx"' '20140109154406115.pdf"'
 '20140109154437503.pdf"' '20140123113558664.pdf"'
 '20140606115234642.pdf"' '20141205095115685.pdf"'
 '20151105084108731.pdf"'
 'Abilene Truck Status - Acquired from Mattress Source.msg"'
 'Additional Title Transfer Info Needed.msg"'
 'Additional Truck Info Needed - Due_ Noon 05_02_2013.msg"'
 'April 25, 2014.pdf"' 'AR Renewal JNAMB80H05AN50271 011314.pdf"'
 'Atlanta GA 7000 -1995 Ford TK.pdf"' 'Auto Schedule as of 10.10.12.xls"'
 'Auto Schedule as of 11.5.13. sent for renewal.xls"'
 'Boise ID 82000 Insp.pdf"' 'Boise truck[1].pdf"'
 'Central ID 89000 Insp.pdf"' 'CHECKLIST FOR VEHICLE TRANSFERS.xlsx"'
 'CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.14.xlsx"'
 'CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx"'
 'Chicago Truck Information.xlsx"'
 'Copy of Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls"'
 'Copy of Q2-2013 Truck Inventory Update JK Revised.xlsx"'
 'Copy of Researched Vehicle Data.xlsx"' 'Ford 1.docx"' 'Ford 2.docx"'
 'FW_ #76000 Carolina Coast Truck.msg"'
 'FW_ _Important_  Mattress Firm Truck - Columbus (174).msg"'
 'FW_ OBX Truck.msg"'
 'FW_ Old 53 foot Trailer parked outside warehouse_.msg"'
 'FW_ Please take a look (151).msg"'
 'FW_ Purchase of mattress source pick up truck.msg"'
 'FW_ Titles and BOS - Greenville_ SC.msg"'
 'FW_ Truck title help - Pittsburgh.msg"'
 'FW_ Vehicle Citation (153).msg"' 'Fw_ Vehicle Information (155).msg"'
 'FW_ VIN # for truck.msg"' 'FW_ W_ Texas trucks (189).msg"'
 'Fwd_ Truck status.msg"' 'Fwd_ Trucks with expired tags.msg"'
 'Fwd_ Vehicle Information.msg"' 'HAA Invoice 1204.pdf"'
 'HAA Invoice 1207.pdf"' 'HAA Invoice 1215.pdf"' 'HAA Invoice 1216.pdf"'
 'HAA Status.xls"' 'Hino.docx"' 'IN inspection form 39530.pdf"'
 'Maine.pdf"' 'Maine0001.pdf"' 'Mattress Firm Auto Parts Schedule.xlsx"'
 'Mattress Inc 2014 Final Vehicle List.xlsx"'
 'Mattress Liquidator Trucks.xls"'
 'Mattress World aka Steelers Truck Titles.pdf"' 'Mebane trucks.pdf"'
 'Mf tax.pdf"'
 'MFI_Hawks_Schedules to Asset Purchase Agreement_Vehicles.pdf"'
 'Northern IN 102000 Insp.pdf"' 'Ohio Vehicle Verification.pdf"'
 'P1-2013 Truck Detail.xlsx"' 'P1-2013 Truck Inventory Update.xlsx"'
 'P1-2013 Truck Inventory.xlsx"' 'P1-2013 Truck Moves.xlsx"'
 'P1-2013 Trucks.xlsx"' 'P3-2013 Truck Inventory Update.xlsx"'
 'P3-2013 Truck Inventory.xlsx"' 'P3-2013 Trucks.xlsx"'
 'PD01-FY2014 Truck Inventory Update 043014.xlsx"'
 'Penske Lease List_032612.xls"' 'Phoenix Titles.msg"'
 'Proj Hawk - Truck Requirements.xls"' 'Q2-2013 Truck HAA 112213.xls"'
 'Q2-2013 Truck Inventory HAA 112213.xls"'
 'Q2-2013 Truck Inventory Update 081913 - 12 16 13.xls"'
 'Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls"'
 'Q2-2013 Truck Inventory Update 081913.xls"'
 'Q2-2013 Truck Inventory Update.xlsx"' 'Q2-2013 Truck Inventory.xlsx"'
 'Q2-2013 Trucks.xls"' 'Re_ #76000 Carolina Coast Truck (95).msg"'
 'RE_ 2 HINO TRUCK REGISTRATIONS.msg"'
 'RE_ Abilene Truck Status - Acquired from Mattress Source.msg"'
 'Re_ FW_ Truck title help - Pittsburgh.msg"' 'RE_ Greenville F150s.msg"'
 'RE_ Jax Whse Truck Title (90).msg"'
 'RE_ Mattress Firm - Truck Status (163).msg"'
 'RE_ Mattress Firm Vehicle Titles.msg"'
 'RE_ Mattress Liquidators - Second Amendment to TSA (44).msg"'
 'RE_ Miami Trucks- Need Titles changed to register.msg"'
 'RE_ MK Trucks (75).msg"'
 'RE_ Old 53 foot Trailer parked outside warehouse_ (113).msg"'
 'Re_ Please take a look (149).msg"'
 'Re_ Purchase of mattress source pick up truck (121).msg"'
 'RE_ REGISTRATION (115).msg"' 'RE_ Titles and BOS - Greenville_ SC.msg"'
 'RE_ Truck (103).msg"' 'RE_ Truck For Sale (73).msg"'
 'RE_ Truck for Sale.msg"' 'RE_ Truck in West TX (26).msg"'
 'RE_ Truck Mileage - Newly Acquired Truck (72).msg"'
 'RE_ Truck Purchase  (140).msg"' 'RE_ Trucks - Status (53).msg"'
 'RE_ Trucks with expired tags.msg"' 'RE_ Vehicle Citation.msg"'
 'RE_ W_ Texas trucks.msg"' 'Reg. Vin#0178.pdf"'
 'Scanned Truck Titles 11.03.14.pdf"' 'tix.pdf"' 'truck Data.pdf"'
 'Truck Info.pdf"' 'Truck inspection 2013.pdf"' 'Trucks Info.pdf"'
 'trucks.pdf"' 'Vehicle (073000) Details.xlsx"' 'Vehicle (073000).xlsx"'
 'Vehicle Citation.pdf"' 'Vehicle Inventory Spreadsheet 08 19 13.xls"'
 'Vehicle Inventory Spreadsheet.xls"' 'Vehicle Titles Received.pdf"'
 'Vehicles Inventory Spreadsheet.xls"'
 'VH Report for Kamal - F12 P11.xlsx"'
 '01-17-2013 - Mattress Firm - Adhoc #50358.xlsx"'
 '01-17-2013 - Mattress Firm - Adhoc.xlsx"']






LEASE MATURITY DATE [                          'NaT' '2014-09-29T00:00:00.000000000'
 '2014-08-30T00:00:00.000000000' '2015-05-25T00:00:00.000000000'
 '2016-10-17T00:00:00.000000000']






Estimated Pick Up Date [nan datetime.datetime(2013, 4, 2, 0, 0) 'ASAP'
 datetime.datetime(2013, 4, 10, 0, 0)]






In Service Date [nan datetime.datetime(2004, 4, 1, 0, 0)
 datetime.datetime(2004, 4, 8, 0, 0) datetime.datetime(2004, 4, 15, 0, 0)
 datetime.datetime(2004, 4, 21, 0, 0) datetime.datetime(2007, 7, 6, 0, 0)
 datetime.datetime(2007, 7, 12, 0, 0) datetime.datetime(2007, 8, 10, 0, 0)
 datetime.datetime(2004, 3, 22, 0, 0) datetime.datetime(2004, 4, 5, 0, 0)
 datetime.datetime(2004, 4, 6, 0, 0) 'Replaced 422147, 604700 returned'
 'Replaced 422144' 'Replaced 422146' datetime.datetime(2004, 3, 31, 0, 0)
 datetime.datetime(2004, 4, 14, 0, 0) datetime.datetime(2007, 6, 27, 0, 0)
 datetime.datetime(2007, 9, 26, 0, 0)]






License Plate Expiration Date [nan]






If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI? [nan]






PIS [                          'NaT' '1998-01-12T00:00:00.000000000'
 '2000-09-13T00:00:00.000000000' '2000-10-25T00:00:00.000000000'
 '2000-12-22T00:00:00.000000000' '2001-11-26T00:00:00.000000000'
 '2000-02-15T00:00:00.000000000' '2001-12-15T00:00:00.000000000'
 '2000-02-23T00:00:00.000000000' '2000-04-30T00:00:00.000000000'
 '2001-06-01T00:00:00.000000000' '1998-05-21T00:00:00.000000000'
 '1998-02-25T00:00:00.000000000' '2000-05-15T00:00:00.000000000'
 '2000-05-26T00:00:00.000000000' '2000-03-31T00:00:00.000000000'
 '2001-06-30T00:00:00.000000000' '2001-04-17T00:00:00.000000000'
 '1997-01-15T00:00:00.000000000' '1998-02-28T00:00:00.000000000'
 '2000-04-05T00:00:00.000000000' '2000-08-19T00:00:00.000000000'
 '2000-09-18T00:00:00.000000000' '2000-10-16T00:00:00.000000000'
 '2000-11-14T00:00:00.000000000' '2000-02-29T00:00:00.000000000'
 '2002-03-03T00:00:00.000000000' '2002-03-30T00:00:00.000000000'
 '2002-04-15T00:00:00.000000000' '2002-04-30T00:00:00.000000000'
 '2002-05-22T00:00:00.000000000' '2002-05-28T00:00:00.000000000'
 '2002-06-27T00:00:00.000000000' '2002-12-31T00:00:00.000000000'
 '2003-04-23T00:00:00.000000000' '2003-05-27T00:00:00.000000000'
 '2003-06-17T00:00:00.000000000' '2003-10-28T00:00:00.000000000'
 '2004-05-04T00:00:00.000000000' '2004-05-19T00:00:00.000000000'
 '2004-05-26T00:00:00.000000000' '2004-05-27T00:00:00.000000000'
 '2004-06-01T00:00:00.000000000' '2004-06-30T00:00:00.000000000'
 '2004-06-18T00:00:00.000000000' '2004-07-05T00:00:00.000000000'
 '2004-06-14T00:00:00.000000000' '2004-07-22T00:00:00.000000000'
 '2004-07-30T00:00:00.000000000' '2004-08-30T00:00:00.000000000'
 '2004-09-13T00:00:00.000000000' '2004-09-14T00:00:00.000000000'
 '2004-11-02T00:00:00.000000000' '2004-12-15T00:00:00.000000000'
 '2005-01-03T00:00:00.000000000' '2005-01-27T00:00:00.000000000'
 '2005-01-31T00:00:00.000000000' '2005-04-12T00:00:00.000000000'
 '2005-05-31T00:00:00.000000000' '2005-06-27T00:00:00.000000000'
 '2006-06-21T00:00:00.000000000' '2006-11-28T00:00:00.000000000'
 '2006-11-29T00:00:00.000000000' '2007-02-27T00:00:00.000000000'
 '2007-05-21T00:00:00.000000000' '2007-12-17T00:00:00.000000000'
 '2007-11-28T00:00:00.000000000' '2007-06-06T00:00:00.000000000'
 '2007-10-23T00:00:00.000000000' '2010-12-01T00:00:00.000000000'
 '2005-02-28T00:00:00.000000000' '2004-12-31T00:00:00.000000000'
 '2004-08-31T00:00:00.000000000' '2007-05-29T00:00:00.000000000'
 '2012-09-25T00:00:00.000000000']






Purchase Date [                          'NaT' '2012-12-11T00:00:00.000000000']

In [51]:
(6-df[df.columns[[12,14,18,22,31,33]]].isnull().sum(axis = 1)).value_counts()

0    2976
1     483
2      55
dtype: int64

## Pick up the Date Columns

In [33]:
for i, col in enumerate(CL.columns):
    print (i, col)

0 FileName
1 Index of Sheet
2 SheetName
3 row Contains Information
4 headerrow
5 number of record
6 Vin
7 VIN #
8 Original In-Service Date
9 Contract Expiration Date
10 Schedule A Date
11 Lease Date
12 License Plate State
13 VIN No.
14 State
15 Registration Expiration Date
16 US DOT Expiration Date
17 Date Added to Insurance
18 Garaged State
19 Will this vehicle cross any state lines while traveling? If so, which ones?
20 Auto ID Card Sent
21 DATE ACQUIRED
22 STATE OF ISSUE
23 VIN # VERIFICATION
24 VIN#
25 NO TRUCKS - Moving OKC truck to here
26 In Service
27 2012 Tax Bill. VIN#1186 and 2378.pdf"
28 VIN
29 LEASE MATURITY DATE
30 Estimated Pick Up Date
31 State.1
32 In Service Date
33 States Traveled
34 License Plate Expiration Date
35 If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI?
36 PIS
37 Detailed Description
38 Purchase Date

### Selected Date columns

In [41]:
CL.columns[[8,9,10,11,15,16,17,20,21,26,29,30,32,34,36,38]]

Index(['Original In-Service Date', 'Contract Expiration Date',
       'Schedule A Date', 'Lease Date', 'Registration Expiration Date',
       'US DOT Expiration Date', 'Date Added to Insurance',
       'Auto ID Card Sent', 'DATE ACQUIRED', 'In Service',
       'LEASE MATURITY DATE', 'Estimated Pick Up Date', 'In Service Date',
       'License Plate Expiration Date', 'PIS', 'Purchase Date'],
      dtype='object')

In [43]:
for a in [col for col in CL.columns if col not in CL.columns[[0,1,2,3,4,5,6,7,13,24,28,37,12,14,18,22,31,33,8,9,10,11,15,16,17,20,21,26,29,30,32,34,36,38]]]:
    print(a, CL[a].unique(),'\n\n\n\n\n\n')

Will this vehicle cross any state lines while traveling? If so, which ones? [nan 'washingington cnty' 'Emailed Justin Cassell 10/26 for missing info'
 'Mattress Xpress - need more info on location contact person'
 '9/11/12 asked Corinna for plate number' 'Inter-State (OH/IN/PN)']






VIN # VERIFICATION [nan 'NOT REQ' 'REQUIRED']






NO TRUCKS - Moving OKC truck to here [nan 'NO TRUCKS' 'Included with VB' 'NEED INFO - FILE WAS CORRUPT'
 'NEED FILE INSTEAD OF EMAIL PICTURE']






2012 Tax Bill. VIN#1186 and 2378.pdf" [nan '2012 Veh Tax Bill. VIN#1186 and 2378.pdf"'
 '2014-15 Auto Schedule.xlsx"'
 '2014Q2 Truck Inventory Update 2014-07-28.xlsx"' '20140109154406115.pdf"'
 '20140109154437503.pdf"' '20140123113558664.pdf"'
 '20140606115234642.pdf"' '20141205095115685.pdf"'
 '20151105084108731.pdf"'
 'Abilene Truck Status - Acquired from Mattress Source.msg"'
 'Additional Title Transfer Info Needed.msg"'
 'Additional Truck Info Needed - Due_ Noon 05_02_2013.msg"'
 'April 25, 2014.pdf"' 'AR Renewal JNAMB80H05AN50271 011314.pdf"'
 'Atlanta GA 7000 -1995 Ford TK.pdf"' 'Auto Schedule as of 10.10.12.xls"'
 'Auto Schedule as of 11.5.13. sent for renewal.xls"'
 'Boise ID 82000 Insp.pdf"' 'Boise truck[1].pdf"'
 'Central ID 89000 Insp.pdf"' 'CHECKLIST FOR VEHICLE TRANSFERS.xlsx"'
 'CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.14.xlsx"'
 'CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx"'
 'Chicago Truck Information.xlsx"'
 'Copy of Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls"'
 'Copy of Q2-2013 Truck Inventory Update JK Revised.xlsx"'
 'Copy of Researched Vehicle Data.xlsx"' 'Ford 1.docx"' 'Ford 2.docx"'
 'FW_ #76000 Carolina Coast Truck.msg"'
 'FW_ _Important_  Mattress Firm Truck - Columbus (174).msg"'
 'FW_ OBX Truck.msg"'
 'FW_ Old 53 foot Trailer parked outside warehouse_.msg"'
 'FW_ Please take a look (151).msg"'
 'FW_ Purchase of mattress source pick up truck.msg"'
 'FW_ Titles and BOS - Greenville_ SC.msg"'
 'FW_ Truck title help - Pittsburgh.msg"'
 'FW_ Vehicle Citation (153).msg"' 'Fw_ Vehicle Information (155).msg"'
 'FW_ VIN # for truck.msg"' 'FW_ W_ Texas trucks (189).msg"'
 'Fwd_ Truck status.msg"' 'Fwd_ Trucks with expired tags.msg"'
 'Fwd_ Vehicle Information.msg"' 'HAA Invoice 1204.pdf"'
 'HAA Invoice 1207.pdf"' 'HAA Invoice 1215.pdf"' 'HAA Invoice 1216.pdf"'
 'HAA Status.xls"' 'Hino.docx"' 'IN inspection form 39530.pdf"'
 'Maine.pdf"' 'Maine0001.pdf"' 'Mattress Firm Auto Parts Schedule.xlsx"'
 'Mattress Inc 2014 Final Vehicle List.xlsx"'
 'Mattress Liquidator Trucks.xls"'
 'Mattress World aka Steelers Truck Titles.pdf"' 'Mebane trucks.pdf"'
 'Mf tax.pdf"'
 'MFI_Hawks_Schedules to Asset Purchase Agreement_Vehicles.pdf"'
 'Northern IN 102000 Insp.pdf"' 'Ohio Vehicle Verification.pdf"'
 'P1-2013 Truck Detail.xlsx"' 'P1-2013 Truck Inventory Update.xlsx"'
 'P1-2013 Truck Inventory.xlsx"' 'P1-2013 Truck Moves.xlsx"'
 'P1-2013 Trucks.xlsx"' 'P3-2013 Truck Inventory Update.xlsx"'
 'P3-2013 Truck Inventory.xlsx"' 'P3-2013 Trucks.xlsx"'
 'PD01-FY2014 Truck Inventory Update 043014.xlsx"'
 'Penske Lease List_032612.xls"' 'Phoenix Titles.msg"'
 'Proj Hawk - Truck Requirements.xls"' 'Q2-2013 Truck HAA 112213.xls"'
 'Q2-2013 Truck Inventory HAA 112213.xls"'
 'Q2-2013 Truck Inventory Update 081913 - 12 16 13.xls"'
 'Q2-2013 Truck Inventory Update 081913 - 12.16.13.xls"'
 'Q2-2013 Truck Inventory Update 081913.xls"'
 'Q2-2013 Truck Inventory Update.xlsx"' 'Q2-2013 Truck Inventory.xlsx"'
 'Q2-2013 Trucks.xls"' 'Re_ #76000 Carolina Coast Truck (95).msg"'
 'RE_ 2 HINO TRUCK REGISTRATIONS.msg"'
 'RE_ Abilene Truck Status - Acquired from Mattress Source.msg"'
 'Re_ FW_ Truck title help - Pittsburgh.msg"' 'RE_ Greenville F150s.msg"'
 'RE_ Jax Whse Truck Title (90).msg"'
 'RE_ Mattress Firm - Truck Status (163).msg"'
 'RE_ Mattress Firm Vehicle Titles.msg"'
 'RE_ Mattress Liquidators - Second Amendment to TSA (44).msg"'
 'RE_ Miami Trucks- Need Titles changed to register.msg"'
 'RE_ MK Trucks (75).msg"'
 'RE_ Old 53 foot Trailer parked outside warehouse_ (113).msg"'
 'Re_ Please take a look (149).msg"'
 'Re_ Purchase of mattress source pick up truck (121).msg"'
 'RE_ REGISTRATION (115).msg"' 'RE_ Titles and BOS - Greenville_ SC.msg"'
 'RE_ Truck (103).msg"' 'RE_ Truck For Sale (73).msg"'
 'RE_ Truck for Sale.msg"' 'RE_ Truck in West TX (26).msg"'
 'RE_ Truck Mileage - Newly Acquired Truck (72).msg"'
 'RE_ Truck Purchase  (140).msg"' 'RE_ Trucks - Status (53).msg"'
 'RE_ Trucks with expired tags.msg"' 'RE_ Vehicle Citation.msg"'
 'RE_ W_ Texas trucks.msg"' 'Reg. Vin#0178.pdf"'
 'Scanned Truck Titles 11.03.14.pdf"' 'tix.pdf"' 'truck Data.pdf"'
 'Truck Info.pdf"' 'Truck inspection 2013.pdf"' 'Trucks Info.pdf"'
 'trucks.pdf"' 'Vehicle (073000) Details.xlsx"' 'Vehicle (073000).xlsx"'
 'Vehicle Citation.pdf"' 'Vehicle Inventory Spreadsheet 08 19 13.xls"'
 'Vehicle Inventory Spreadsheet.xls"' 'Vehicle Titles Received.pdf"'
 'Vehicles Inventory Spreadsheet.xls"'
 'VH Report for Kamal - F12 P11.xlsx"'
 '01-17-2013 - Mattress Firm - Adhoc #50358.xlsx"'
 '01-17-2013 - Mattress Firm - Adhoc.xlsx"']






If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI? [nan]

In [50]:
(16-df[df.columns[[8,9,10,11,15,16,17,20,21,26,29,30,32,34,36,38]]].isnull().sum(axis = 1)).value_counts()

0    2943
1     528
4      24
2      19
dtype: int64

## Final Clean Output with VIN, Date, and State

In [10]:
df['StandardVIN'] = StandardVIN.values
df

                                                                                         FileName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               1   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               2   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               3   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               4   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               5   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               6   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               7   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               8   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               9   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               10  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               11  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               12  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               0   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               1   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               2   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               3   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               4   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               5   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               6   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               7   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               8   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               9   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               10  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               11  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
01-17-2013 - Mattress Firm - Adhoc.xlsx        0          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               1          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               2          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               3          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               4          01-17-2013 - Mattress Firm - Adhoc.xlsx
...                                                                                           ...
Vehicle Inventory Spreadsheet.xls              18               Vehicle Inventory Spreadsheet.xls
                                               19               Vehicle Inventory Spreadsheet.xls
                                               20               Vehicle Inventory Spreadsheet.xls
                                               21               Vehicle Inventory Spreadsheet.xls
                                               22               Vehicle Inventory Spreadsheet.xls
                                               0                Vehicle Inventory Spreadsheet.xls
Vehicles Inventory Spreadsheet.xls             0               Vehicles Inventory Spreadsheet.xls
                                               1               Vehicles Inventory Spreadsheet.xls
                                               2               Vehicles Inventory Spreadsheet.xls
                                               3               Vehicles Inventory Spreadsheet.xls
                                               4               Vehicles Inventory Spreadsheet.xls
                                               5               Vehicles Inventory Spreadsheet.xls
                                               6               Vehicles Inventory Spreadsheet.xls
                                               7               Vehicles Inventory Spreadsheet.xls
                                               8               Vehicles Inventory Spreadsheet.xls
                                               9               Vehicles Inventory Spreadsheet.xls
                                               10              Vehicles Inventory Spreadsheet.xls
                                               11              Vehicles Inventory Spreadsheet.xls
                                               12              Vehicles Inventory Spreadsheet.xls
                                               13              Vehicles Inventory Spreadsheet.xls
                                               14              Vehicles Inventory Spreadsheet.xls
                                               15              Vehicles Inventory Spreadsheet.xls
                                               16              Vehicles Inventory Spreadsheet.xls
                                               17              Vehicles Inventory Spreadsheet.xls
                                               18              Vehicles Inventory Spreadsheet.xls
                                               19              Vehicles Inventory Spreadsheet.xls
                                               20              Vehicles Inventory Spreadsheet.xls
                                               21              Vehicles Inventory Spreadsheet.xls
                                               22              Vehicles Inventory Spreadsheet.xls
                                               0               Vehicles Inventory Spreadsheet.xls

                                                   Index of Sheet  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                1
                                               1                1
                                               2                1
                                               3                1
                                               4                1
                                               5                1
                                               6                1
                                               7                1
                                               8                1
                                               9                1
                                               10               1
                                               11               1
                                               12               1
                                               0                2
                                               1                2
                                               2                2
                                               3                2
                                               4                2
                                               5                2
                                               6                2
                                               7                2
                                               8                2
                                               9                2
                                               10               2
                                               11               2
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                1
                                               1                1
                                               2                1
                                               3                1
                                               4                1
...                                                           ...
Vehicle Inventory Spreadsheet.xls              18               1
                                               19               1
                                               20               1
                                               21               1
                                               22               1
                                               0                2
Vehicles Inventory Spreadsheet.xls             0                1
                                               1                1
                                               2                1
                                               3                1
                                               4                1
                                               5                1
                                               6                1
                                               7                1
                                               8                1
                                               9                1
                                               10               1
                                               11               1
                                               12               1
                                               13               1
                                               14               1
                                               15               1
                                               16               1
                                               17               1
                                               18               1
                                               19               1
                                               20               1
                                               21               1
                                               22               1
                                               0                2

                                                      SheetName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0             CC
                                               1             CC
                                               2             CC
                                               3             CC
                                               4             CC
                                               5             CC
                                               6             CC
                                               7             CC
                                               8             CC
                                               9             CC
                                               10            CC
                                               11            CC
                                               12            CC
                                               0         Output
                                               1         Output
                                               2         Output
                                               3         Output
                                               4         Output
                                               5         Output
                                               6         Output
                                               7         Output
                                               8         Output
                                               9         Output
                                               10        Output
                                               11        Output
01-17-2013 - Mattress Firm - Adhoc.xlsx        0             CC
                                               1             CC
                                               2             CC
                                               3             CC
                                               4             CC
...                                                         ...
Vehicle Inventory Spreadsheet.xls              18  Summary Page
                                               19  Summary Page
                                               20  Summary Page
                                               21  Summary Page
                                               22  Summary Page
                                               0         Sheet1
Vehicles Inventory Spreadsheet.xls             0   Summary Page
                                               1   Summary Page
                                               2   Summary Page
                                               3   Summary Page
                                               4   Summary Page
                                               5   Summary Page
                                               6   Summary Page
                                               7   Summary Page
                                               8   Summary Page
                                               9   Summary Page
                                               10  Summary Page
                                               11  Summary Page
                                               12  Summary Page
                                               13  Summary Page
                                               14  Summary Page
                                               15  Summary Page
                                               16  Summary Page
                                               17  Summary Page
                                               18  Summary Page
                                               19  Summary Page
                                               20  Summary Page
                                               21  Summary Page
                                               22  Summary Page
                                               0         Sheet1

                                                  row Contains Information  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes
                                               0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
...                                                                    ...
Vehicle Inventory Spreadsheet.xls              18                      Yes
                                               19                      Yes
                                               20                      Yes
                                               21                      Yes
                                               22                      Yes
                                               0                        NO
Vehicles Inventory Spreadsheet.xls             0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes
                                               13                      Yes
                                               14                      Yes
                                               15                      Yes
                                               16                      Yes
                                               17                      Yes
                                               18                      Yes
                                               19                      Yes
                                               20                      Yes
                                               21                      Yes
                                               22                      Yes
                                               0                        NO

                                                   headerrow  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0        14.0
                                               1        14.0
                                               2        14.0
                                               3        14.0
                                               4        14.0
                                               5        14.0
                                               6        14.0
                                               7        14.0
                                               8        14.0
                                               9        14.0
                                               10       14.0
                                               11       14.0
                                               12       14.0
                                               0         0.0
                                               1         0.0
                                               2         0.0
                                               3         0.0
                                               4         0.0

In [67]:
for i, a in enumerate(df.columns):
    print(i, a)

0 FileName
1 Index of Sheet
2 SheetName
3 row Contains Information
4 headerrow
5 number of record
6 Vin
7 VIN #
8 Original In-Service Date
9 Contract Expiration Date
10 Schedule A Date
11 Lease Date
12 License Plate State
13 VIN No.
14 State
15 Registration Expiration Date
16 US DOT Expiration Date
17 Date Added to Insurance
18 Garaged State
19 Will this vehicle cross any state lines while traveling? If so, which ones?
20 Auto ID Card Sent
21 DATE ACQUIRED
22 STATE OF ISSUE
23 VIN # VERIFICATION
24 VIN#
25 NO TRUCKS - Moving OKC truck to here
26 In Service
27 2012 Tax Bill. VIN#1186 and 2378.pdf"
28 VIN
29 LEASE MATURITY DATE
30 Estimated Pick Up Date
31 State.1
32 In Service Date
33 States Traveled
34 License Plate Expiration Date
35 If Moving to Different State - Original VIN Inspection Paperwork Rcvd by MFI?
36 PIS
37 Detailed Description
38 Purchase Date
39 # of  Value from selected VIN columns
40 StandardVIN

In [85]:
df[df['# of  Value from selected VIN columns'] == 2].iloc[:,[0,1,2,3,4,5,40,12,14,18,22,31,33,8,9,10,11,15,16,17,20,21,26,29,30,32,34,36,38]]

                                                                                         FileName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               1   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               2   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               3   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               4   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               5   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               6   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               7   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               8   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               9   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               10  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               11  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               12  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
01-17-2013 - Mattress Firm - Adhoc.xlsx        0          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               1          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               2          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               3          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               4          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               5          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               6          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               7          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               8          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               9          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               10         01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               11         01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               12         01-17-2013 - Mattress Firm - Adhoc.xlsx

                                                   Index of Sheet SheetName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                1        CC
                                               1                1        CC
                                               2                1        CC
                                               3                1        CC
                                               4                1        CC
                                               5                1        CC
                                               6                1        CC
                                               7                1        CC
                                               8                1        CC
                                               9                1        CC
                                               10               1        CC
                                               11               1        CC
                                               12               1        CC
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                1        CC
                                               1                1        CC
                                               2                1        CC
                                               3                1        CC
                                               4                1        CC
                                               5                1        CC
                                               6                1        CC
                                               7                1        CC
                                               8                1        CC
                                               9                1        CC
                                               10               1        CC
                                               11               1        CC
                                               12               1        CC

                                                  row Contains Information  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes

                                                   headerrow  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0        14.0
                                               1        14.0
                                               2        14.0
                                               3        14.0
                                               4        14.0
                                               5        14.0
                                               6        14.0
                                               7        14.0
                                               8        14.0
                                               9        14.0
                                               10       14.0
                                               11       14.0
                                               12       14.0
01-17-2013 - Mattress Firm - Adhoc.xlsx        0        14.0
                                               1        14.0
                                               2        14.0
                                               3        14.0
                                               4        14.0
                                               5        14.0
                                               6        14.0
                                               7        14.0
                                               8        14.0
                                               9        14.0
                                               10       14.0
                                               11       14.0
                                               12       14.0

                                                   number of record  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0               13.0
                                               1               13.0
                                               2               13.0
                                               3               13.0
                                               4               13.0
                                               5               13.0
                                               6               13.0
                                               7               13.0
                                               8               13.0
                                               9               13.0
                                               10              13.0
                                               11              13.0
                                               12              13.0
01-17-2013 - Mattress Firm - Adhoc.xlsx        0               13.0
                                               1               13.0
                                               2               13.0
                                               3               13.0
                                               4               13.0
                                               5               13.0
                                               6               13.0
                                               7               13.0
                                               8               13.0
                                               9               13.0
                                               10              13.0
                                               11              13.0
                                               12              13.0

                                                                                       StandardVIN  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0    Unit Usage (Power, etc.);Usage (Power /Reefer)
                                               1          In-Service Date;Original In-Service Date
                                               2          Expiration Date;Contract Expiration Date
                                               3                  Schedule "A" Number;Schedule A #
                                               4                 Schedule "A" Date;Schedule A Date
                                               5                             Lease Type;Lease Type
                                               6                          VLSA/VMA Date;Lease Date
                                               7           Current Fixed Charge;Current Fixed Rate
                                               8       Current Mileage Charge;Current Mileage Rate
                                               9      Current Mileage Reading;Last Mileage Reading
                                               10     Current License Plate Number;License Plate #
                                               11  Current License Plate State;License Plate State
                                               12  Gross Vehicle Weight;Vehicle Mfr's Gross Weight
01-17-2013 - Mattress Firm - Adhoc.xlsx        0    Unit Usage (Power, etc.);Usage (Power /Reefer)
                                               1          In-Service Date;Original In-Service Date
                                               2          Expiration Date;Contract Expiration Date
                                               3                  Schedule "A" Number;Schedule A #
                                               4                 Schedule "A" Date;Schedule A Date
                                               5                             Lease Type;Lease Type
                                               6                          VLSA/VMA Date;Lease Date
                                               7           Current Fixed Charge;Current Fixed Rate
                                               8       Current Mileage Charge;Current Mileage Rate
                                               9      Current Mileage Reading;Last Mileage Reading
                                               10     Current License Plate Number;License Plate #
                                               11  Current License Plate State;License Plate State
                                               12  Gross Vehicle Weight;Vehicle Mfr's Gross Weight

                                                  License Plate State State  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                  NaN   NaN
                                               1                  NaN   NaN
                                               2                  NaN   NaN
                                               3                  NaN   NaN
                                               4                  NaN   NaN
                                               5                  NaN   NaN
                                               6                  NaN   NaN
                                               7                  NaN   NaN
                                               8                  NaN   NaN
                                               9                  NaN   NaN
                                               10                 NaN   NaN
                                               11                 NaN   NaN
                                               12                 NaN   NaN
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                  NaN   NaN
                                               1                  NaN   NaN
                                               2                  NaN   NaN
                                               3                  NaN   NaN
                                               4                  NaN   NaN
                                               5                  NaN   NaN
                                               6                  NaN   NaN
                                               7                  NaN   NaN
                                               8                  NaN   NaN
                                               9                  NaN   NaN
                                               10                 NaN   NaN
                                               11                 NaN   NaN
                                               12                 NaN   NaN

                                                  Garaged State  ...  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0            NaN  ...
                                               1            NaN  ...
                                               2            NaN  ...
                                               3            NaN  ...
                                               4            NaN  ...
                                               5            NaN  ...
                                               6            NaN  ...
                                               7            NaN  ...
                                               8            NaN  ...
                                               9            NaN  ...
                                               10           NaN  ...
                                               11           NaN  ...
                                               12           NaN  ...
01-17-2013 - Mattress Firm - Adhoc.xlsx        0            NaN  ...
                                               1            NaN  ...
                                               2            NaN  ...
                                               3            NaN  ...
                                               4            NaN  ...
                                               5            NaN  ...
                                               6            NaN  ...
                                               7            NaN  ...
                                               8            NaN  ...
                                               9            NaN  ...
                                               10           NaN  ...
                                               11           NaN  ...
                                               12           NaN  ...

                                                  Date Added to Insurance  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                      NaN
                                               1                      NaN
                                               2                      NaN
                                               3                      NaN
                                               4                      NaN
                                               5                      NaN
                                               6                      NaN
                                               7                      NaN
                                               8                      NaN
                                               9                      NaN
                                               10                     NaN
                                               11                     NaN
                                               12                     NaN
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                      NaN
                                               1                      NaN
                                               2                      NaN
                                               3                      NaN
                                               4                      NaN
                                               5                      NaN
                                               6                      NaN
                                               7                      NaN
                                               8                      NaN
                                               9                      NaN
                                               10                     NaN
                                               11                     NaN
                                               12                     NaN

                                                  Auto ID Card Sent  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                NaT
                                               1                NaT
                                               2                NaT
                                               3                NaT
                                               4                NaT
                                               5                NaT
                                               6                NaT
                                               7                NaT
                                               8                NaT
                                               9                NaT
                                               10               NaT
                                               11               NaT
                                               12               NaT
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                NaT
                                               1                NaT
                                               2                NaT

In [23]:
Result_with_date_state = df[df['# of  Value from selected VIN columns'] == 2].iloc[:,[0,1,2,3,4,5,40,12,14,18,22,31,33,8,9,10,11,15,16,17,20,21,26,29,30,32,34,36,38]]
Result_with_date_state

                                                                                         FileName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               1   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               2   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               3   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               4   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               5   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               6   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               7   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               8   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               9   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               10  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               11  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               12  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
01-17-2013 - Mattress Firm - Adhoc.xlsx        0          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               1          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               2          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               3          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               4          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               5          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               6          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               7          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               8          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               9          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               10         01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               11         01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               12         01-17-2013 - Mattress Firm - Adhoc.xlsx

                                                   Index of Sheet SheetName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                1        CC
                                               1                1        CC
                                               2                1        CC
                                               3                1        CC
                                               4                1        CC
                                               5                1        CC
                                               6                1        CC
                                               7                1        CC
                                               8                1        CC
                                               9                1        CC
                                               10               1        CC
                                               11               1        CC
                                               12               1        CC
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                1        CC
                                               1                1        CC
                                               2                1        CC
                                               3                1        CC
                                               4                1        CC
                                               5                1        CC
                                               6                1        CC
                                               7                1        CC
                                               8                1        CC
                                               9                1        CC
                                               10               1        CC
                                               11               1        CC
                                               12               1        CC

                                                  row Contains Information  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes

                                                   headerrow  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0        14.0
                                               1        14.0
                                               2        14.0
                                               3        14.0
                                               4        14.0
                                               5        14.0
                                               6        14.0
                                               7        14.0
                                               8        14.0
                                               9        14.0
                                               10       14.0
                                               11       14.0
                                               12       14.0
01-17-2013 - Mattress Firm - Adhoc.xlsx        0        14.0
                                               1        14.0
                                               2        14.0
                                               3        14.0
                                               4        14.0
                                               5        14.0
                                               6        14.0
                                               7        14.0
                                               8        14.0
                                               9        14.0
                                               10       14.0
                                               11       14.0
                                               12       14.0

                                                   number of record  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0               13.0
                                               1               13.0
                                               2               13.0
                                               3               13.0
                                               4               13.0
                                               5               13.0
                                               6               13.0
                                               7               13.0
                                               8               13.0
                                               9               13.0
                                               10              13.0
                                               11              13.0
                                               12              13.0
01-17-2013 - Mattress Firm - Adhoc.xlsx        0               13.0
                                               1               13.0
                                               2               13.0
                                               3               13.0
                                               4               13.0
                                               5               13.0
                                               6               13.0
                                               7               13.0
                                               8               13.0
                                               9               13.0
                                               10              13.0
                                               11              13.0
                                               12              13.0

                                                                                       StandardVIN  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0    Unit Usage (Power, etc.);Usage (Power /Reefer)
                                               1          In-Service Date;Original In-Service Date
                                               2          Expiration Date;Contract Expiration Date
                                               3                  Schedule "A" Number;Schedule A #
                                               4                 Schedule "A" Date;Schedule A Date
                                               5                             Lease Type;Lease Type
                                               6                          VLSA/VMA Date;Lease Date
                                               7           Current Fixed Charge;Current Fixed Rate
                                               8       Current Mileage Charge;Current Mileage Rate
                                               9      Current Mileage Reading;Last Mileage Reading
                                               10     Current License Plate Number;License Plate #
                                               11  Current License Plate State;License Plate State
                                               12  Gross Vehicle Weight;Vehicle Mfr's Gross Weight
01-17-2013 - Mattress Firm - Adhoc.xlsx        0    Unit Usage (Power, etc.);Usage (Power /Reefer)
                                               1          In-Service Date;Original In-Service Date
                                               2          Expiration Date;Contract Expiration Date
                                               3                  Schedule "A" Number;Schedule A #
                                               4                 Schedule "A" Date;Schedule A Date
                                               5                             Lease Type;Lease Type
                                               6                          VLSA/VMA Date;Lease Date
                                               7           Current Fixed Charge;Current Fixed Rate
                                               8       Current Mileage Charge;Current Mileage Rate
                                               9      Current Mileage Reading;Last Mileage Reading
                                               10     Current License Plate Number;License Plate #
                                               11  Current License Plate State;License Plate State
                                               12  Gross Vehicle Weight;Vehicle Mfr's Gross Weight

                                                  License Plate State State  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                  NaN   NaN
                                               1                  NaN   NaN
                                               2                  NaN   NaN
                                               3                  NaN   NaN
                                               4                  NaN   NaN
                                               5                  NaN   NaN
                                               6                  NaN   NaN
                                               7                  NaN   NaN
                                               8                  NaN   NaN
                                               9                  NaN   NaN
                                               10                 NaN   NaN
                                               11                 NaN   NaN
                                               12                 NaN   NaN
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                  NaN   NaN
                                               1                  NaN   NaN
                                               2                  NaN   NaN
                                               3                  NaN   NaN
                                               4                  NaN   NaN
                                               5                  NaN   NaN
                                               6                  NaN   NaN
                                               7                  NaN   NaN
                                               8                  NaN   NaN
                                               9                  NaN   NaN
                                               10                 NaN   NaN
                                               11                 NaN   NaN
                                               12                 NaN   NaN

                                                  Garaged State  ...  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0            NaN  ...
                                               1            NaN  ...
                                               2            NaN  ...
                                               3            NaN  ...
                                               4            NaN  ...
                                               5            NaN  ...
                                               6            NaN  ...
                                               7            NaN  ...
                                               8            NaN  ...
                                               9            NaN  ...
                                               10           NaN  ...
                                               11           NaN  ...
                                               12           NaN  ...
01-17-2013 - Mattress Firm - Adhoc.xlsx        0            NaN  ...
                                               1            NaN  ...
                                               2            NaN  ...
                                               3            NaN  ...
                                               4            NaN  ...
                                               5            NaN  ...
                                               6            NaN  ...
                                               7            NaN  ...
                                               8            NaN  ...
                                               9            NaN  ...
                                               10           NaN  ...
                                               11           NaN  ...
                                               12           NaN  ...

                                                  Date Added to Insurance  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                      NaN
                                               1                      NaN
                                               2                      NaN
                                               3                      NaN
                                               4                      NaN
                                               5                      NaN
                                               6                      NaN
                                               7                      NaN
                                               8                      NaN
                                               9                      NaN
                                               10                     NaN
                                               11                     NaN
                                               12                     NaN
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                      NaN
                                               1                      NaN
                                               2                      NaN
                                               3                      NaN
                                               4                      NaN
                                               5                      NaN
                                               6                      NaN
                                               7                      NaN
                                               8                      NaN
                                               9                      NaN
                                               10                     NaN
                                               11                     NaN
                                               12                     NaN

                                                  Auto ID Card Sent  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                NaT
                                               1                NaT
                                               2                NaT
                                               3                NaT
                                               4                NaT
                                               5                NaT
                                               6                NaT
                                               7                NaT
                                               8                NaT
                                               9                NaT
                                               10               NaT
                                               11               NaT
                                               12               NaT
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                NaT
                                               1                NaT
                                               2                NaT

## VIN Flag

In [13]:
Flag = pd.Series(None,index = range(len(Result_with_date_state)))
import re

for i, a  in enumerate(Result_with_date_state.StandardVIN.values):
    if re.match('(?=.*[0-9])(?=.*[a-zA-Z])',str(a)):
        Flag[i] = 'Yes'
    else:
        Flag[i] = 'No'
Result_with_date_state['At lease contain one number and a letter'] = Flag.values
Result_with_date_state

                                                                                         FileName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               1   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               2   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               3   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               4   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               5   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               6   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               7   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               8   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               9   01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               10  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
                                               11  01-17-2013 - Mattress Firm - Adhoc #50358.xlsx
01-17-2013 - Mattress Firm - Adhoc.xlsx        0          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               1          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               2          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               3          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               4          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               5          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               6          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               7          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               8          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               9          01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               10         01-17-2013 - Mattress Firm - Adhoc.xlsx
                                               11         01-17-2013 - Mattress Firm - Adhoc.xlsx
2014-15 Auto Schedule.xlsx                     0                       2014-15 Auto Schedule.xlsx
                                               0                       2014-15 Auto Schedule.xlsx
                                               1                       2014-15 Auto Schedule.xlsx
                                               2                       2014-15 Auto Schedule.xlsx
                                               3                       2014-15 Auto Schedule.xlsx
                                               4                       2014-15 Auto Schedule.xlsx
...                                                                                           ...
Vehicle Inventory Spreadsheet.xls              16               Vehicle Inventory Spreadsheet.xls
                                               17               Vehicle Inventory Spreadsheet.xls
                                               18               Vehicle Inventory Spreadsheet.xls
                                               19               Vehicle Inventory Spreadsheet.xls
                                               20               Vehicle Inventory Spreadsheet.xls
                                               21               Vehicle Inventory Spreadsheet.xls
                                               22               Vehicle Inventory Spreadsheet.xls
Vehicles Inventory Spreadsheet.xls             0               Vehicles Inventory Spreadsheet.xls
                                               1               Vehicles Inventory Spreadsheet.xls
                                               2               Vehicles Inventory Spreadsheet.xls
                                               3               Vehicles Inventory Spreadsheet.xls
                                               4               Vehicles Inventory Spreadsheet.xls
                                               5               Vehicles Inventory Spreadsheet.xls
                                               6               Vehicles Inventory Spreadsheet.xls
                                               7               Vehicles Inventory Spreadsheet.xls
                                               8               Vehicles Inventory Spreadsheet.xls
                                               9               Vehicles Inventory Spreadsheet.xls
                                               10              Vehicles Inventory Spreadsheet.xls
                                               11              Vehicles Inventory Spreadsheet.xls
                                               12              Vehicles Inventory Spreadsheet.xls
                                               13              Vehicles Inventory Spreadsheet.xls
                                               14              Vehicles Inventory Spreadsheet.xls
                                               15              Vehicles Inventory Spreadsheet.xls
                                               16              Vehicles Inventory Spreadsheet.xls
                                               17              Vehicles Inventory Spreadsheet.xls
                                               18              Vehicles Inventory Spreadsheet.xls
                                               19              Vehicles Inventory Spreadsheet.xls
                                               20              Vehicles Inventory Spreadsheet.xls
                                               21              Vehicles Inventory Spreadsheet.xls
                                               22              Vehicles Inventory Spreadsheet.xls

                                                   Index of Sheet  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                2
                                               1                2
                                               2                2
                                               3                2
                                               4                2
                                               5                2
                                               6                2
                                               7                2
                                               8                2
                                               9                2
                                               10               2
                                               11               2
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                2
                                               1                2
                                               2                2
                                               3                2
                                               4                2
                                               5                2
                                               6                2
                                               7                2
                                               8                2
                                               9                2
                                               10               2
                                               11               2
2014-15 Auto Schedule.xlsx                     0                1
                                               0                2
                                               1                2
                                               2                2
                                               3                2
                                               4                2
...                                                           ...
Vehicle Inventory Spreadsheet.xls              16               1
                                               17               1
                                               18               1
                                               19               1
                                               20               1
                                               21               1
                                               22               1
Vehicles Inventory Spreadsheet.xls             0                1
                                               1                1
                                               2                1
                                               3                1
                                               4                1
                                               5                1
                                               6                1
                                               7                1
                                               8                1
                                               9                1
                                               10               1
                                               11               1
                                               12               1
                                               13               1
                                               14               1
                                               15               1
                                               16               1
                                               17               1
                                               18               1
                                               19               1
                                               20               1
                                               21               1
                                               22               1

                                                          SheetName  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0             Output
                                               1             Output
                                               2             Output
                                               3             Output
                                               4             Output
                                               5             Output
                                               6             Output
                                               7             Output
                                               8             Output
                                               9             Output
                                               10            Output
                                               11            Output
01-17-2013 - Mattress Firm - Adhoc.xlsx        0             Output
                                               1             Output
                                               2             Output
                                               3             Output
                                               4             Output
                                               5             Output
                                               6             Output
                                               7             Output
                                               8             Output
                                               9             Output
                                               10            Output
                                               11            Output
2014-15 Auto Schedule.xlsx                     0        Update Form
                                               0   Summary 08.01.14
                                               1   Summary 08.01.14
                                               2   Summary 08.01.14
                                               3   Summary 08.01.14
                                               4   Summary 08.01.14
...                                                             ...
Vehicle Inventory Spreadsheet.xls              16      Summary Page
                                               17      Summary Page
                                               18      Summary Page
                                               19      Summary Page
                                               20      Summary Page
                                               21      Summary Page
                                               22      Summary Page
Vehicles Inventory Spreadsheet.xls             0       Summary Page
                                               1       Summary Page
                                               2       Summary Page
                                               3       Summary Page
                                               4       Summary Page
                                               5       Summary Page
                                               6       Summary Page
                                               7       Summary Page
                                               8       Summary Page
                                               9       Summary Page
                                               10      Summary Page
                                               11      Summary Page
                                               12      Summary Page
                                               13      Summary Page
                                               14      Summary Page
                                               15      Summary Page
                                               16      Summary Page
                                               17      Summary Page
                                               18      Summary Page
                                               19      Summary Page
                                               20      Summary Page
                                               21      Summary Page
                                               22      Summary Page

                                                  row Contains Information  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
01-17-2013 - Mattress Firm - Adhoc.xlsx        0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
2014-15 Auto Schedule.xlsx                     0                       Yes
                                               0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
...                                                                    ...
Vehicle Inventory Spreadsheet.xls              16                      Yes
                                               17                      Yes
                                               18                      Yes
                                               19                      Yes
                                               20                      Yes
                                               21                      Yes
                                               22                      Yes
Vehicles Inventory Spreadsheet.xls             0                       Yes
                                               1                       Yes
                                               2                       Yes
                                               3                       Yes
                                               4                       Yes
                                               5                       Yes
                                               6                       Yes
                                               7                       Yes
                                               8                       Yes
                                               9                       Yes
                                               10                      Yes
                                               11                      Yes
                                               12                      Yes
                                               13                      Yes
                                               14                      Yes
                                               15                      Yes
                                               16                      Yes
                                               17                      Yes
                                               18                      Yes
                                               19                      Yes
                                               20                      Yes
                                               21                      Yes
                                               22                      Yes

                                                   headerrow  \
01-17-2013 - Mattress Firm - Adhoc #50358.xlsx 0         0.0
                                               1         0.0
                                               2         0.0
                                               3         0.0
                                               4         0.0
                                               5         0.0
                                               6         0.0
                                               7         0.0
                                               8         0.0
                                               9         0.0
                                               10        0.0
                                               11        0.0
01-17-2013 - Mattress Firm - Adhoc.xlsx        0         0.0
                                               1         0.0

In [21]:
CL.groupby(['FileName','SheetName']).size().reset_index()

,FileName,SheetName,0
0,01-17-2013 - Mattress Firm - Adhoc #50358.xlsx,CC,13
1,01-17-2013 - Mattress Firm - Adhoc #50358.xlsx,Output,12
2,01-17-2013 - Mattress Firm - Adhoc.xlsx,CC,13
3,01-17-2013 - Mattress Firm - Adhoc.xlsx,Output,12
4,2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...,1 - Capital Lease RF,1
5,2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...,2 - Note Payable RF,1
6,2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...,PPEC,1
7,2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...,PY,1
8,2.4.29 2.4.10_Debt Schedules_MLI (No APC Data)...,Sheet1,1
9,2014-15 Auto Schedule.xlsx,Sheet2,1
10,2014-15 Auto Schedule.xlsx,Summary 08.01.14,160
11,2014-15 Auto Schedule.xlsx,Update Form,1
12,2014Q2 Truck Inventory Update 2014-07-28.xlsx,Sheet2,1
13,2014Q2 Truck Inventory Update 2014-07-28.xlsx,Summary 08.01.14,160
14,2014Q2 Truck Inventory Update 2014-07-28.xlsx,Update Form,1
15,Auto Schedule as of 10.10.12.xls,Auto Schedule 11-12,43
16,Auto Schedule as of 10.10.12.xls,Sheet2,42
17,Auto Schedule as of 11.5.13. sent for renewal.xls,P7 Update,36
18,Auto Schedule as of 11.5.13. sent for renewal.xls,Update Form,1
19,CHECKLIST FOR VEHICLE TRANSFERS.xlsx,Sheet1,13
20,CHECKLIST FOR VEHICLE TRANSFERS.xlsx,Sheet2,1
21,CHECKLIST FOR VEHICLE TRANSFERS.xlsx,Sheet3,1
22,CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.1...,Sheet1,13
23,CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.1...,Sheet2,1
24,CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.1...,Sheet3,1
25,CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx,Sheet1,13
26,CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx,Sheet2,1
27,CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx,Sheet3,1
28,Chicago Truck Information.xlsx,Sheet1,7
29,Chicago Truck Information.xlsx,Sheet2,1
...,...,...,...
399,Q2-2013 Trucks.xls,Houston 001000,2
400,Q2-2013 Trucks.xls,Jacksonville 016000,1
401,Q2-2013 Trucks.xls,Mebane 1300,5
402,Q2-2013 Trucks.xls,Miami North 052000,1
403,Q2-2013 Trucks.xls,Miami South 052099,3
404,Q2-2013 Trucks.xls,OKC 041000,2
405,Q2-2013 Trucks.xls,P7 Update,44
406,Q2-2013 Trucks.xls,Pensacola 081000,1
407,Q2-2013 Trucks.xls,Phoenix 02900,4
408,Q2-2013 Trucks.xls,Pocatello 089000,1
409,Q2-2013 Trucks.xls,Portland 085000,2
410,Q2-2013 Trucks.xls,South Bend 102000,5
411,Q2-2013 Trucks.xls,Spokane 101000,1
412,Q2-2013 Trucks.xls,St. Petersburg 025000,2
413,Q2-2013 Trucks.xls,Update Form,1
414,Q2-2013 Trucks.xls,Whiteville 076000,2
415,VH Report for Kamal - F12 P11.xlsx,Sheet1,157
416,Vehicle (073000) Details.xlsx,Sheet1,1
417,Vehicle (073000) Details.xlsx,Sheet2,1
418,Vehicle (073000) Details.xlsx,Sheet3,1
419,Vehicle (073000).xlsx,Sheet1,1
420,Vehicle (073000).xlsx,Sheet2,1
421,Vehicle (073000).xlsx,Sheet3,1
422,Vehicle Inventory Spreadsheet 08 19 13.xls,Addtl,3
423,Vehicle Inventory Spreadsheet 08 19 13.xls,Sheet1,1
424,Vehicle Inventory Spreadsheet 08 19 13.xls,Summary Page,21
425,Vehicle Inventory Spreadsheet.xls,Sheet1,1
426,Vehicle Inventory Spreadsheet.xls,Summary Page,23
427,Vehicles Inventory Spreadsheet.xls,Sheet1,1
428,Vehicles Inventory Spreadsheet.xls,Summary Page,23

In [20]:
Result_with_date_state[Result_with_date_state['At lease contain one number and a letter'] == 'Yes'].groupby(['FileName','SheetName']).size().reset_index()

,FileName,SheetName,0
0,01-17-2013 - Mattress Firm - Adhoc #50358.xlsx,Output,11
1,01-17-2013 - Mattress Firm - Adhoc.xlsx,Output,11
2,2014-15 Auto Schedule.xlsx,Summary 08.01.14,76
3,2014-15 Auto Schedule.xlsx,Update Form,1
4,2014Q2 Truck Inventory Update 2014-07-28.xlsx,Summary 08.01.14,76
5,2014Q2 Truck Inventory Update 2014-07-28.xlsx,Update Form,1
6,Auto Schedule as of 10.10.12.xls,Auto Schedule 11-12,32
7,Auto Schedule as of 10.10.12.xls,Sheet2,31
8,Auto Schedule as of 11.5.13. sent for renewal.xls,P7 Update,36
9,Auto Schedule as of 11.5.13. sent for renewal.xls,Update Form,1
10,CHECKLIST FOR VEHICLE TRANSFERS.xlsx,Sheet1,10
11,CHECKLIST FOR VEHICLE TRANSFERS_update 11.05.1...,Sheet1,10
12,CHECKLIST FOR VEHICLE TRANSFERS_update.xlsx,Sheet1,10
13,Copy of Q2-2013 Truck Inventory Update 081913 ...,Atlanta 007000,3
14,Copy of Q2-2013 Truck Inventory Update 081913 ...,Boise 082000,1
15,Copy of Q2-2013 Truck Inventory Update 081913 ...,Charleston 040000,2
16,Copy of Q2-2013 Truck Inventory Update 081913 ...,Charlotte 024000,8
17,Copy of Q2-2013 Truck Inventory Update 081913 ...,Columbia 033000,3
18,Copy of Q2-2013 Truck Inventory Update 081913 ...,Columbus 037000,1
19,Copy of Q2-2013 Truck Inventory Update 081913 ...,Davenport 054000,2
20,Copy of Q2-2013 Truck Inventory Update 081913 ...,Fayetteville 072000,2
21,Copy of Q2-2013 Truck Inventory Update 081913 ...,Greenville 038000,3
22,Copy of Q2-2013 Truck Inventory Update 081913 ...,Houston 001000,2
23,Copy of Q2-2013 Truck Inventory Update 081913 ...,Jacksonville 016000,1
24,Copy of Q2-2013 Truck Inventory Update 081913 ...,Mebane 1300,5
25,Copy of Q2-2013 Truck Inventory Update 081913 ...,Miami North 052000,1
26,Copy of Q2-2013 Truck Inventory Update 081913 ...,Miami South 052099,3
27,Copy of Q2-2013 Truck Inventory Update 081913 ...,OKC 041000,2
28,Copy of Q2-2013 Truck Inventory Update 081913 ...,P7 Update,43
29,Copy of Q2-2013 Truck Inventory Update 081913 ...,Pensacola 081000,1
...,...,...,...
336,Q2-2013 Trucks.xls,Atlanta 007000,3
337,Q2-2013 Trucks.xls,Boise 082000,1
338,Q2-2013 Trucks.xls,Charleston 040000,2
339,Q2-2013 Trucks.xls,Charlotte 024000,8
340,Q2-2013 Trucks.xls,Columbia 033000,3
341,Q2-2013 Trucks.xls,Columbus 037000,1
342,Q2-2013 Trucks.xls,Davenport 054000,2
343,Q2-2013 Trucks.xls,Fayetteville 072000,2
344,Q2-2013 Trucks.xls,Greenville 038000,3
345,Q2-2013 Trucks.xls,Houston 001000,2
346,Q2-2013 Trucks.xls,Jacksonville 016000,1
347,Q2-2013 Trucks.xls,Mebane 1300,5
348,Q2-2013 Trucks.xls,Miami North 052000,1
349,Q2-2013 Trucks.xls,Miami South 052099,3
350,Q2-2013 Trucks.xls,OKC 041000,2
351,Q2-2013 Trucks.xls,P7 Update,43
352,Q2-2013 Trucks.xls,Pensacola 081000,1
353,Q2-2013 Trucks.xls,Phoenix 02900,3
354,Q2-2013 Trucks.xls,Pocatello 089000,1
355,Q2-2013 Trucks.xls,Portland 085000,2
356,Q2-2013 Trucks.xls,South Bend 102000,2
357,Q2-2013 Trucks.xls,Spokane 101000,1
358,Q2-2013 Trucks.xls,St. Petersburg 025000,2
359,Q2-2013 Trucks.xls,Update Form,1
360,Q2-2013 Trucks.xls,Whiteville 076000,2
361,VH Report for Kamal - F12 P11.xlsx,Sheet1,18
362,Vehicle Inventory Spreadsheet 08 19 13.xls,Addtl,3
363,Vehicle Inventory Spreadsheet 08 19 13.xls,Summary Page,20
364,Vehicle Inventory Spreadsheet.xls,Summary Page,23
365,Vehicles Inventory Spreadsheet.xls,Summary Page,23

In [78]:
Result_with_date_state.to_excel(r'C:\Users\FFR0103\Desktop\My files\WORK\Auto part\Mattress Firm\Output\Result_with_date_state.xlsx', index = False)